# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

#Define to 1, to build a special version of libkernel that does not contain any runtime patches (useful for loaders/resident programs).
KERNEL_NO_PATCHES = 1

EE_SRC_DIR = $(PS2SDKSRC)/ee/kernel/src/

include $(PS2SDKSRC)/ee/kernel/Makefile
