# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_SRC_DIR = $(PS2SDKSRC)/iop/hdd/apa/src/

IOP_BIN ?= ps2hdd-bdm.irx

APA_USE_DEV9 ?= 0
APA_USE_ATAD ?= 0
APA_USE_BDM ?= 1

include $(PS2SDKSRC)/iop/hdd/apa/Makefile
