/*
# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.
*/

#ifndef _ACATA_INTERNAL_H
#define _ACATA_INTERNAL_H

#include <acata.h>
#include <irx_imports.h>

#define ACATA_A_DATA			0xB6000000 // Read/Write PIO data bytes

#define ACATA_R_DATA         	*((acAtaReg)0xB6000000) // Read/Write PIO data bytes
#define ACATA_R_FEATURES     	*((acAtaReg)0xB6010000) // [W] Used to control command specific interface features.
#define ACATA_R_ERROR        	ACATA_R_FEATURES		// [R] Used to retrieve any error generated by the last ATA command executed.	
#define ACATA_R_SECCNT       	*((acAtaReg)0xB6020000) // Number of sectors to read/write (0 is a special value).
#define ACATA_R_SECNUM       	*((acAtaReg)0xB6030000) // This is CHS / LBA28 / LBA48 specific.
#define ACATA_R_CYL_LOW      	*((acAtaReg)0xB6040000) // Partial Disk Sector address.
#define ACATA_R_CYL_HIGH     	*((acAtaReg)0xB6050000) // Partial Disk Sector address.
#define ACATA_R_DRIVE_HEAD   	*((acAtaReg)0xB6060000) // Used to select a drive and/or head. Supports extra address/flag bits. [`ACATA_UNIT0`, `ACATA_UNIT1`]
#define ACATA_R_STATUS       	*((acAtaReg)0xB6070000) // [R] Used to read the current status.
#define ACATA_R_COMMAND      	ACATA_R_STATUS			// [W] Used to send ATA commands to the device.
#define ACATA_R_ALT_STATUS   	*((acAtaReg)0xB6160000) // [R] A duplicate of the Status Register which does not affect interrupts.
#define ACATA_R_DEVCONTROL  	ACATA_R_ALT_STATUS		// [W] Used to reset the bus or enable/disable interrupts.


struct ata_softc
{
	acQueueHeadData requestq;
	acUint32 active;
	acInt32 thid;
	struct ac_ata_h *atah;
	acUint16 cprio;
	acUint16 prio;
	acTimerData timer;
};

struct ata_dma
{
	acDmaData ad_dma;
	acAtaT ad_ata;
	acInt32 ad_thid;
	acInt32 ad_result;
	acUint32 ad_state;
};

struct atapi_dma
{
	acDmaData ad_dma;
	acAtapiT ad_atapi;
	acInt32 ad_thid;
	acInt32 ad_result;
	acUint32 ad_state;
};

struct atapi_sense
{
	// cppcheck-suppress unusedStructMember
	acUint8 s_valid;
	// cppcheck-suppress unusedStructMember
	acUint8 s_segnum;
	acUint8 s_key;
	// cppcheck-suppress unusedStructMember
	acUint8 s_info[4];
	// cppcheck-suppress unusedStructMember
	acUint8 s_aslen;
	// cppcheck-suppress unusedStructMember
	acUint8 s_csi[4];
	acUint8 s_asc;
	acUint8 s_ascq;
	// cppcheck-suppress unusedStructMember
	acUint8 s_fruc;
	// cppcheck-suppress unusedStructMember
	acUint8 s_sks[3];
};

extern int ata_request(struct ac_ata_h *atah, int (*wakeup)(int thid));
extern int ata_probe(acAtaReg atareg);
extern int acAtaModuleStart(int argc, char **argv);
extern int acAtaModuleStop();
extern int acAtaModuleRestart(int argc, char **argv);
extern int acAtaModuleStatus();

#endif
