PS2SDK: iop/cdvd/cdvdman/include/cdvdman.h File Reference
cdvdman.h File Reference
#include <types.h>
#include <irx.h>
#include <libcdvd-common.h>
Data Structures
struct cdvdman_dma3_parameter_
struct cdvdman_internal_struct_
Macros
#define cdvdman_IMPORTS_start DECLARE_IMPORT_TABLE(cdvdman, 1, 1)
#define cdvdman_IMPORTS_end END_IMPORT_TABLE
#define I_sceCdInit DECLARE_IMPORT(4, sceCdInit)
#define I_sceCdStandby DECLARE_IMPORT(5, sceCdStandby)
#define I_sceCdRead DECLARE_IMPORT(6, sceCdRead)
#define I_sceCdSeek DECLARE_IMPORT(7, sceCdSeek)
#define I_sceCdGetError DECLARE_IMPORT(8, sceCdGetError)
#define I_sceCdGetToc DECLARE_IMPORT(9, sceCdGetToc)
#define I_sceCdSearchFile DECLARE_IMPORT(10, sceCdSearchFile)
#define I_sceCdSync DECLARE_IMPORT(11, sceCdSync)
#define I_sceCdGetDiskType DECLARE_IMPORT(12, sceCdGetDiskType)
#define I_sceCdDiskReady DECLARE_IMPORT(13, sceCdDiskReady)
#define I_sceCdTrayReq DECLARE_IMPORT(14, sceCdTrayReq)
#define I_sceCdStop DECLARE_IMPORT(15, sceCdStop)
#define I_sceCdPosToInt DECLARE_IMPORT(16, sceCdPosToInt)
#define I_sceCdIntToPos DECLARE_IMPORT(17, sceCdIntToPos)
#define I_sceCdGetToc2 DECLARE_IMPORT(19, sceCdGetToc2)
#define I_sceCdReadDVDV DECLARE_IMPORT(20, sceCdReadDVDV)
#define I_sceCdCheckCmd DECLARE_IMPORT(21, sceCdCheckCmd)
#define I_sceCdRI DECLARE_IMPORT(22, sceCdRI)
#define I_sceCdWI DECLARE_IMPORT(23, sceCdWI)
#define I_sceCdReadClock DECLARE_IMPORT(24, sceCdReadClock)
#define I_sceCdWriteClock DECLARE_IMPORT(25, sceCdWriteClock)
#define I_sceCdReadNVM DECLARE_IMPORT(26, sceCdReadNVM)
#define I_sceCdWriteNVM DECLARE_IMPORT(27, sceCdWriteNVM)
#define I_sceCdStatus DECLARE_IMPORT(28, sceCdStatus)
#define I_sceCdApplySCmd DECLARE_IMPORT(29, sceCdApplySCmd)
#define I_sceCdSetHDMode DECLARE_IMPORT(30, sceCdSetHDMode)
#define I_sceCdOpenConfig DECLARE_IMPORT(31, sceCdOpenConfig)
#define I_sceCdCloseConfig DECLARE_IMPORT(32, sceCdCloseConfig)
#define I_sceCdReadConfig DECLARE_IMPORT(33, sceCdReadConfig)
#define I_sceCdWriteConfig DECLARE_IMPORT(34, sceCdWriteConfig)
#define I_sceCdReadKey DECLARE_IMPORT(35, sceCdReadKey)
#define I_sceCdDecSet DECLARE_IMPORT(36, sceCdDecSet)
#define I_sceCdCallback DECLARE_IMPORT(37, sceCdCallback)
#define I_sceCdPause DECLARE_IMPORT(38, sceCdPause)
#define I_sceCdBreak DECLARE_IMPORT(39, sceCdBreak)
#define I_sceCdReadCDDA DECLARE_IMPORT(40, sceCdReadCDDA)
#define I_sceCdReadConsoleID DECLARE_IMPORT(41, sceCdReadConsoleID)
#define I_sceCdWriteConsoleID DECLARE_IMPORT(42, sceCdWriteConsoleID)
#define I_sceCdMV DECLARE_IMPORT(43, sceCdMV)
#define I_sceCdGetReadPos DECLARE_IMPORT(44, sceCdGetReadPos)
#define I_sceCdCtrlADout DECLARE_IMPORT(45, sceCdCtrlADout)
#define I_sceCdNop DECLARE_IMPORT(46, sceCdNop)
#define I_sceGetFsvRbuf DECLARE_IMPORT(47, sceGetFsvRbuf)
#define I_sceCdstm0Cb DECLARE_IMPORT(48, sceCdstm0Cb)
#define I_sceCdstm1Cb DECLARE_IMPORT(49, sceCdstm1Cb)
#define I_sceCdSC DECLARE_IMPORT(50, sceCdSC)
#define I_sceCdRC DECLARE_IMPORT(51, sceCdRC)
#define I_sceCdForbidDVDP DECLARE_IMPORT(52, sceCdForbidDVDP)
#define I_sceCdReadSUBQ DECLARE_IMPORT(53, sceCdReadSUBQ)
#define I_sceCdApplyNCmd DECLARE_IMPORT(54, sceCdApplyNCmd)
#define I_sceCdAutoAdjustCtrl DECLARE_IMPORT(55, sceCdAutoAdjustCtrl)
#define I_sceCdStInit DECLARE_IMPORT(56, sceCdStInit)
#define I_sceCdStRead DECLARE_IMPORT(57, sceCdStRead)
#define I_sceCdStSeek DECLARE_IMPORT(58, sceCdStSeek)
#define I_sceCdStStart DECLARE_IMPORT(59, sceCdStStart)
#define I_sceCdStStat DECLARE_IMPORT(60, sceCdStStat)
#define I_sceCdStStop DECLARE_IMPORT(61, sceCdStStop)
#define I_sceCdRead0 DECLARE_IMPORT(62, sceCdRead0)
#define I_sceCdRV DECLARE_IMPORT(63, sceCdRV)
#define I_sceCdRM DECLARE_IMPORT(64, sceCdRM)
#define I_sceCdWM DECLARE_IMPORT(65, sceCdWM)
#define I_sceCdReadChain DECLARE_IMPORT(66, sceCdReadChain)
#define I_sceCdStPause DECLARE_IMPORT(67, sceCdStPause)
#define I_sceCdStResume DECLARE_IMPORT(68, sceCdStResume)
#define I_sceCdForbidRead DECLARE_IMPORT(69, sceCdForbidRead)
#define I_sceCdBootCertify DECLARE_IMPORT(70, sceCdBootCertify)
#define I_sceCdSpinCtrlIOP DECLARE_IMPORT(71, sceCdSpinCtrlIOP)
#define I_sceCdBlueLEDCtl DECLARE_IMPORT(72, sceCdBlueLEDCtl)
#define I_sceCdCancelPOffRdy DECLARE_IMPORT(73, sceCdCancelPOffRdy)
#define I_sceCdPowerOff DECLARE_IMPORT(74, sceCdPowerOff)
#define I_sceCdMmode DECLARE_IMPORT(75, sceCdMmode)
#define I_sceCdReadFull DECLARE_IMPORT(76, sceCdReadFull)
#define I_sceCdStSeekF DECLARE_IMPORT(77, sceCdStSeekF)
#define I_sceCdPOffCallback DECLARE_IMPORT(78, sceCdPOffCallback)
#define I_sceCdReadDiskID DECLARE_IMPORT(79, sceCdReadDiskID)
#define I_sceCdReadGUID DECLARE_IMPORT(80, sceCdReadGUID)
#define I_sceCdSetTimeout DECLARE_IMPORT(81, sceCdSetTimeout)
#define I_sceCdReadModelID DECLARE_IMPORT(82, sceCdReadModelID)
#define I_sceCdReadDvdDualInfo DECLARE_IMPORT(83, sceCdReadDvdDualInfo)
#define I_sceCdLayerSearchFile DECLARE_IMPORT(84, sceCdLayerSearchFile)
#define I_sceCdStatus2 DECLARE_IMPORT(90, sceCdStatus2)
#define I_sceCdReadWakeUpTime DECLARE_IMPORT(109, sceCdReadWakeUpTime)
#define I_sceCdWriteWakeUpTime DECLARE_IMPORT(110, sceCdWriteWakeUpTime)
#define I_sceCdApplySCmd2 DECLARE_IMPORT(112, sceCdApplySCmd2)
#define I_sceCdRE DECLARE_IMPORT(114, sceCdRE)
#define I_sceCdRcBypassCtl DECLARE_IMPORT(115, sceCdRcBypassCtl)
#define I_sceCdSendSCmd1D DECLARE_IMPORT(116, sceCdSendSCmd1D)
#define I_sceRemote2_7 DECLARE_IMPORT(117, sceRemote2_7)
#define I_sceCdSetLEDsMode DECLARE_IMPORT(120, sceCdSetLEDsMode)
#define I_sceCdApplySCmd3 DECLARE_IMPORT(125, sceCdApplySCmd3)
#define I_sceRemote2_7Get DECLARE_IMPORT(128, sceRemote2_7Get)
#define I_sceCdReadPS1BootParam DECLARE_IMPORT(148, sceCdReadPS1BootParam)
#define I_sceCdSetFanProfile DECLARE_IMPORT(150, sceCdSetFanProfile)
#define I_cdvdman_152_get_temperature DECLARE_IMPORT(152, cdvdman_152_get_temperature)
#define I_sceCdChgSys DECLARE_IMPORT(154, sceCdChgSys)
#define I_sceCdNoticeGameStart DECLARE_IMPORT(156, sceCdNoticeGameStart)
#define I_sceCdDeobfuscateUsingUniqueKey DECLARE_IMPORT(161, sceCdDeobfuscateUsingUniqueKey)
#define I_sceCdXLEDCtl DECLARE_IMPORT(163, sceCdXLEDCtl)
#define I_sceCdBuzzerCtl DECLARE_IMPORT(165, sceCdBuzzerCtl)
#define I_cdvdman_167_atapi2dragon DECLARE_IMPORT(167, cdvdman_167_atapi2dragon)
#define I_cdvdman_169_dragon2atapi DECLARE_IMPORT(169, cdvdman_169_dragon2atapi)
#define I_sceCdXBSPowerCtl DECLARE_IMPORT(171, sceCdXBSPowerCtl)
#define I_sceCdSetAtapiEjectCallback DECLARE_IMPORT(173, sceCdSetAtapiEjectCallback)
#define I_sceCdSetMediumRemoval DECLARE_IMPORT(175, sceCdSetMediumRemoval)
#define I_sceCdGetMediumRemoval DECLARE_IMPORT(177, sceCdGetMediumRemoval)
#define I_sceCdDoesUniqueKeyExist DECLARE_IMPORT(179, sceCdDoesUniqueKeyExist)
#define I_sceCdXDVRPReset DECLARE_IMPORT(181, sceCdXDVRPReset)
#define I_sceCdGetWakeUpReason DECLARE_IMPORT(183, sceCdGetWakeUpReason)
#define I_sceCdReadRegionParams DECLARE_IMPORT(189, sceCdReadRegionParams)
#define I_sceCdWriteRegionParams DECLARE_IMPORT(191, sceCdWriteRegionParams)
Typedefs
typedef struct cdvdman_dma3_parameter_ cdvdman_dma3_parameter_t
typedef struct cdvdman_internal_struct_ cdvdman_internal_struct_t
Functions
int sceCdCheckCmd (void)
int sceCdNop (void)
void * sceGetFsvRbuf (void)
int sceCdstm0Cb (void(*p)(int val))
int sceCdstm1Cb (void(*p)(int val))
int sceCdSC (int code, int *param)
int sceCdRC (sceCdCLOCK *clock)
int sceCdRead0 (u32 lsn, u32 sectors, void *buffer, sceCdRMode *mode, int csec, void *callback)
int sceCdRV (u32 lsn, u32 sectors, void *buf, sceCdRMode *mode, int arg5, void *cb)
int sceCdApplySCmd2 (u8 cmdNum, const void *inBuff, unsigned long int inBuffSize, void *outBuff)
int sceCdApplySCmd3 (u8 cmdNum, const void *inBuff, unsigned long int inBuffSize, void *outBuff)
int sceCdSpinCtrlIOP (u32 speed)
void * sceCdSetAtapiEjectCallback (int(*cb)(int reason, void *userdata), void *userdata)
int sceCdReadDiskID (unsigned int *id)
int sceCdDeobfuscateUsingUniqueKey (u8 *buffer, unsigned int shiftval, int xorval, u32 *status)
Detailed Description
Definitions and imports for cdvdman
Definition in file cdvdman.h.
Data Structure Documentation
cdvdman_dma3_parameter_
struct cdvdman_dma3_parameter_
Definition at line 53 of file cdvdman.h.
Data Fields
u16 m_dma3_blkwords
u16 m_dma3_blkcount
void * m_dma3_maddress
int(*)(void) m_dma3_callback
u16 m_dma3_csectors
u16 m_cdvdreg_howto
u32 m_dma3_msectors
cdvdman_internal_struct_
struct cdvdman_internal_struct_
Definition at line 64 of file cdvdman.h.
Data Fields
char m_cdvdman_command
unsigned char m_last_error
char m_unused_002
char m_ncmd_intr_count
int m_wait_flag
int m_thread_id
int m_stream_flag
int m_read2_flag
int m_cdvdman_lsn
int m_cdvdman_rbuffer
int m_cdvdman_nsec
int m_cdvdman_csec
int m_cdvdman_rsec
int m_cdvdman_pattern
sceCdRMode m_cdvdman_cdrmode
int m_recover_status
int m_dvd_flag
int m_read_lsn
void * m_read_buf
int m_read_sectors
sceCdRMode m_read_mode
int m_read_chunk_reprocial_32
int m_dintrlsn
void * m_read_callback
int m_read_chunk
char m_scmd_flag
char m_scmd
char m_sdlen
char m_rdlen
char m_scmd_sd[16]
char m_scmd_rd[16]
int m_sync_error
int m_last_read_timeout
int m_power_flag
u32 m_layer_1_lsn
char m_use_toc
char m_opo_or_para
char m_current_dvd
char m_dual_layer_emulation
u32 m_current_dvd_lsn
int m_check_version
int m_dec_shift
int m_dec_state
int m_no_dec_flag
cdvdman_dma3_parameter_t m_dma3_param
int m_cdvdman_dma3sec
int m_drive_interupt_request
u16 m_dec_mode_set
u16 m_dec_mode_last_set
int m_waf_set_test
int m_cd_mode_ps2_atapi
void(*)(int writer_drive) m_cd_atapi_intr_callback
int(*)(void *userdata, int writer_drive) m_chgsys_callback
int m_chgsys_callback_next_disktype
int m_unusedosd1
int m_field_0DC
int m_var_sc_ffffffdb
int m_interupt_read_state
int m_atapi_disk_ejected
int m_cd_inited
int m_medium_removal_state
int m_chgsys_callback_next_disktype_last
int m_chgsys_writer_drive_shell_is_open
int m_unusedosd2[6]
int m_tray_is_open
int m_break_cdvdfsv_readchain
int m_unused[10]
Macro Definition Documentation
cdvdman_IMPORTS_start
#define cdvdman_IMPORTS_start DECLARE_IMPORT_TABLE(cdvdman, 1, 1)
Definition at line 223 of file cdvdman.h.
cdvdman_IMPORTS_end
#define cdvdman_IMPORTS_end END_IMPORT_TABLE
Definition at line 224 of file cdvdman.h.
I_sceCdInit
#define I_sceCdInit DECLARE_IMPORT(4, sceCdInit)
Definition at line 226 of file cdvdman.h.
I_sceCdStandby
#define I_sceCdStandby DECLARE_IMPORT(5, sceCdStandby)
Definition at line 227 of file cdvdman.h.
I_sceCdRead
#define I_sceCdRead DECLARE_IMPORT(6, sceCdRead)
Definition at line 228 of file cdvdman.h.
I_sceCdSeek
#define I_sceCdSeek DECLARE_IMPORT(7, sceCdSeek)
Definition at line 229 of file cdvdman.h.
I_sceCdGetError
#define I_sceCdGetError DECLARE_IMPORT(8, sceCdGetError)
Definition at line 230 of file cdvdman.h.
I_sceCdGetToc
#define I_sceCdGetToc DECLARE_IMPORT(9, sceCdGetToc)
Definition at line 231 of file cdvdman.h.
I_sceCdSearchFile
#define I_sceCdSearchFile DECLARE_IMPORT(10, sceCdSearchFile)
Definition at line 232 of file cdvdman.h.
I_sceCdSync
#define I_sceCdSync DECLARE_IMPORT(11, sceCdSync)
Definition at line 233 of file cdvdman.h.
I_sceCdGetDiskType
#define I_sceCdGetDiskType DECLARE_IMPORT(12, sceCdGetDiskType)
Definition at line 234 of file cdvdman.h.
I_sceCdDiskReady
#define I_sceCdDiskReady DECLARE_IMPORT(13, sceCdDiskReady)
Definition at line 235 of file cdvdman.h.
I_sceCdTrayReq
#define I_sceCdTrayReq DECLARE_IMPORT(14, sceCdTrayReq)
Definition at line 236 of file cdvdman.h.
I_sceCdStop
#define I_sceCdStop DECLARE_IMPORT(15, sceCdStop)
Definition at line 237 of file cdvdman.h.
I_sceCdPosToInt
#define I_sceCdPosToInt DECLARE_IMPORT(16, sceCdPosToInt)
Definition at line 238 of file cdvdman.h.
I_sceCdIntToPos
#define I_sceCdIntToPos DECLARE_IMPORT(17, sceCdIntToPos)
Definition at line 239 of file cdvdman.h.
I_sceCdGetToc2
#define I_sceCdGetToc2 DECLARE_IMPORT(19, sceCdGetToc2)
Definition at line 240 of file cdvdman.h.
I_sceCdReadDVDV
#define I_sceCdReadDVDV DECLARE_IMPORT(20, sceCdReadDVDV)
Definition at line 241 of file cdvdman.h.
I_sceCdCheckCmd
#define I_sceCdCheckCmd DECLARE_IMPORT(21, sceCdCheckCmd)
Definition at line 242 of file cdvdman.h.
I_sceCdRI
#define I_sceCdRI DECLARE_IMPORT(22, sceCdRI)
Definition at line 243 of file cdvdman.h.
I_sceCdWI
#define I_sceCdWI DECLARE_IMPORT(23, sceCdWI)
Definition at line 244 of file cdvdman.h.
I_sceCdReadClock
#define I_sceCdReadClock DECLARE_IMPORT(24, sceCdReadClock)
Definition at line 245 of file cdvdman.h.
I_sceCdWriteClock
#define I_sceCdWriteClock DECLARE_IMPORT(25, sceCdWriteClock)
Definition at line 246 of file cdvdman.h.
I_sceCdReadNVM
#define I_sceCdReadNVM DECLARE_IMPORT(26, sceCdReadNVM)
Definition at line 247 of file cdvdman.h.
I_sceCdWriteNVM
#define I_sceCdWriteNVM DECLARE_IMPORT(27, sceCdWriteNVM)
Definition at line 248 of file cdvdman.h.
I_sceCdStatus
#define I_sceCdStatus DECLARE_IMPORT(28, sceCdStatus)
Definition at line 249 of file cdvdman.h.
I_sceCdApplySCmd
#define I_sceCdApplySCmd DECLARE_IMPORT(29, sceCdApplySCmd)
Definition at line 250 of file cdvdman.h.
I_sceCdSetHDMode
#define I_sceCdSetHDMode DECLARE_IMPORT(30, sceCdSetHDMode)
Definition at line 251 of file cdvdman.h.
I_sceCdOpenConfig
#define I_sceCdOpenConfig DECLARE_IMPORT(31, sceCdOpenConfig)
Definition at line 252 of file cdvdman.h.
I_sceCdCloseConfig
#define I_sceCdCloseConfig DECLARE_IMPORT(32, sceCdCloseConfig)
Definition at line 253 of file cdvdman.h.
I_sceCdReadConfig
#define I_sceCdReadConfig DECLARE_IMPORT(33, sceCdReadConfig)
Definition at line 254 of file cdvdman.h.
I_sceCdWriteConfig
#define I_sceCdWriteConfig DECLARE_IMPORT(34, sceCdWriteConfig)
Definition at line 255 of file cdvdman.h.
I_sceCdReadKey
#define I_sceCdReadKey DECLARE_IMPORT(35, sceCdReadKey)
Definition at line 256 of file cdvdman.h.
I_sceCdDecSet
#define I_sceCdDecSet DECLARE_IMPORT(36, sceCdDecSet)
Definition at line 257 of file cdvdman.h.
I_sceCdCallback
#define I_sceCdCallback DECLARE_IMPORT(37, sceCdCallback)
Definition at line 258 of file cdvdman.h.
I_sceCdPause
#define I_sceCdPause DECLARE_IMPORT(38, sceCdPause)
Definition at line 259 of file cdvdman.h.
I_sceCdBreak
#define I_sceCdBreak DECLARE_IMPORT(39, sceCdBreak)
Definition at line 260 of file cdvdman.h.
I_sceCdReadCDDA
#define I_sceCdReadCDDA DECLARE_IMPORT(40, sceCdReadCDDA)
Definition at line 261 of file cdvdman.h.
I_sceCdReadConsoleID
#define I_sceCdReadConsoleID DECLARE_IMPORT(41, sceCdReadConsoleID)
Definition at line 262 of file cdvdman.h.
I_sceCdWriteConsoleID
#define I_sceCdWriteConsoleID DECLARE_IMPORT(42, sceCdWriteConsoleID)
Definition at line 263 of file cdvdman.h.
I_sceCdMV
#define I_sceCdMV DECLARE_IMPORT(43, sceCdMV)
Definition at line 264 of file cdvdman.h.
I_sceCdGetReadPos
#define I_sceCdGetReadPos DECLARE_IMPORT(44, sceCdGetReadPos)
Definition at line 265 of file cdvdman.h.
I_sceCdCtrlADout
#define I_sceCdCtrlADout DECLARE_IMPORT(45, sceCdCtrlADout)
Definition at line 266 of file cdvdman.h.
I_sceCdNop
#define I_sceCdNop DECLARE_IMPORT(46, sceCdNop)
Definition at line 267 of file cdvdman.h.
I_sceGetFsvRbuf
#define I_sceGetFsvRbuf DECLARE_IMPORT(47, sceGetFsvRbuf)
Definition at line 268 of file cdvdman.h.
I_sceCdstm0Cb
#define I_sceCdstm0Cb DECLARE_IMPORT(48, sceCdstm0Cb)
Definition at line 269 of file cdvdman.h.
I_sceCdstm1Cb
#define I_sceCdstm1Cb DECLARE_IMPORT(49, sceCdstm1Cb)
Definition at line 270 of file cdvdman.h.
I_sceCdSC
#define I_sceCdSC DECLARE_IMPORT(50, sceCdSC)
Definition at line 271 of file cdvdman.h.
I_sceCdRC
#define I_sceCdRC DECLARE_IMPORT(51, sceCdRC)
Definition at line 272 of file cdvdman.h.
I_sceCdForbidDVDP
#define I_sceCdForbidDVDP DECLARE_IMPORT(52, sceCdForbidDVDP)
Definition at line 273 of file cdvdman.h.
I_sceCdReadSUBQ
#define I_sceCdReadSUBQ DECLARE_IMPORT(53, sceCdReadSUBQ)
Definition at line 274 of file cdvdman.h.
I_sceCdApplyNCmd
#define I_sceCdApplyNCmd DECLARE_IMPORT(54, sceCdApplyNCmd)
Definition at line 275 of file cdvdman.h.
I_sceCdAutoAdjustCtrl
#define I_sceCdAutoAdjustCtrl DECLARE_IMPORT(55, sceCdAutoAdjustCtrl)
Definition at line 276 of file cdvdman.h.
I_sceCdStInit
#define I_sceCdStInit DECLARE_IMPORT(56, sceCdStInit)
Definition at line 277 of file cdvdman.h.
I_sceCdStRead
#define I_sceCdStRead DECLARE_IMPORT(57, sceCdStRead)
Definition at line 278 of file cdvdman.h.
I_sceCdStSeek
#define I_sceCdStSeek DECLARE_IMPORT(58, sceCdStSeek)
Definition at line 279 of file cdvdman.h.
I_sceCdStStart
#define I_sceCdStStart DECLARE_IMPORT(59, sceCdStStart)
Definition at line 280 of file cdvdman.h.
I_sceCdStStat
#define I_sceCdStStat DECLARE_IMPORT(60, sceCdStStat)
Definition at line 281 of file cdvdman.h.
I_sceCdStStop
#define I_sceCdStStop DECLARE_IMPORT(61, sceCdStStop)
Definition at line 282 of file cdvdman.h.
I_sceCdRead0
#define I_sceCdRead0 DECLARE_IMPORT(62, sceCdRead0)
Definition at line 283 of file cdvdman.h.
I_sceCdRV
#define I_sceCdRV DECLARE_IMPORT(63, sceCdRV)
Definition at line 284 of file cdvdman.h.
I_sceCdRM
#define I_sceCdRM DECLARE_IMPORT(64, sceCdRM)
Definition at line 285 of file cdvdman.h.
I_sceCdWM
#define I_sceCdWM DECLARE_IMPORT(65, sceCdWM)
Definition at line 286 of file cdvdman.h.
I_sceCdReadChain
#define I_sceCdReadChain DECLARE_IMPORT(66, sceCdReadChain)
Definition at line 287 of file cdvdman.h.
I_sceCdStPause
#define I_sceCdStPause DECLARE_IMPORT(67, sceCdStPause)
Definition at line 288 of file cdvdman.h.
I_sceCdStResume
#define I_sceCdStResume DECLARE_IMPORT(68, sceCdStResume)
Definition at line 289 of file cdvdman.h.
I_sceCdForbidRead
#define I_sceCdForbidRead DECLARE_IMPORT(69, sceCdForbidRead)
Definition at line 290 of file cdvdman.h.
I_sceCdBootCertify
#define I_sceCdBootCertify DECLARE_IMPORT(70, sceCdBootCertify)
Definition at line 291 of file cdvdman.h.
I_sceCdSpinCtrlIOP
#define I_sceCdSpinCtrlIOP DECLARE_IMPORT(71, sceCdSpinCtrlIOP)
Definition at line 292 of file cdvdman.h.
I_sceCdBlueLEDCtl
#define I_sceCdBlueLEDCtl DECLARE_IMPORT(72, sceCdBlueLEDCtl)
Definition at line 293 of file cdvdman.h.
I_sceCdCancelPOffRdy
#define I_sceCdCancelPOffRdy DECLARE_IMPORT(73, sceCdCancelPOffRdy)
Definition at line 294 of file cdvdman.h.
I_sceCdPowerOff
#define I_sceCdPowerOff DECLARE_IMPORT(74, sceCdPowerOff)
Definition at line 295 of file cdvdman.h.
I_sceCdMmode
#define I_sceCdMmode DECLARE_IMPORT(75, sceCdMmode)
Definition at line 296 of file cdvdman.h.
I_sceCdReadFull
#define I_sceCdReadFull DECLARE_IMPORT(76, sceCdReadFull)
Definition at line 298 of file cdvdman.h.
I_sceCdStSeekF
#define I_sceCdStSeekF DECLARE_IMPORT(77, sceCdStSeekF)
Definition at line 299 of file cdvdman.h.
I_sceCdPOffCallback
#define I_sceCdPOffCallback DECLARE_IMPORT(78, sceCdPOffCallback)
Definition at line 300 of file cdvdman.h.
I_sceCdReadDiskID
#define I_sceCdReadDiskID DECLARE_IMPORT(79, sceCdReadDiskID)
Definition at line 301 of file cdvdman.h.
I_sceCdReadGUID
#define I_sceCdReadGUID DECLARE_IMPORT(80, sceCdReadGUID)
Definition at line 302 of file cdvdman.h.
I_sceCdSetTimeout
#define I_sceCdSetTimeout DECLARE_IMPORT(81, sceCdSetTimeout)
Definition at line 303 of file cdvdman.h.
I_sceCdReadModelID
#define I_sceCdReadModelID DECLARE_IMPORT(82, sceCdReadModelID)
Definition at line 304 of file cdvdman.h.
I_sceCdReadDvdDualInfo
#define I_sceCdReadDvdDualInfo DECLARE_IMPORT(83, sceCdReadDvdDualInfo)
Definition at line 305 of file cdvdman.h.
I_sceCdLayerSearchFile
#define I_sceCdLayerSearchFile DECLARE_IMPORT(84, sceCdLayerSearchFile)
Definition at line 306 of file cdvdman.h.
I_sceCdStatus2
#define I_sceCdStatus2 DECLARE_IMPORT(90, sceCdStatus2)
Definition at line 307 of file cdvdman.h.
I_sceCdReadWakeUpTime
#define I_sceCdReadWakeUpTime DECLARE_IMPORT(109, sceCdReadWakeUpTime)
Definition at line 308 of file cdvdman.h.
I_sceCdWriteWakeUpTime
#define I_sceCdWriteWakeUpTime DECLARE_IMPORT(110, sceCdWriteWakeUpTime)
Definition at line 309 of file cdvdman.h.
I_sceCdApplySCmd2
#define I_sceCdApplySCmd2 DECLARE_IMPORT(112, sceCdApplySCmd2)
Definition at line 310 of file cdvdman.h.
I_sceCdRE
#define I_sceCdRE DECLARE_IMPORT(114, sceCdRE)
Definition at line 311 of file cdvdman.h.
I_sceCdRcBypassCtl
#define I_sceCdRcBypassCtl DECLARE_IMPORT(115, sceCdRcBypassCtl)
Definition at line 312 of file cdvdman.h.
I_sceCdSendSCmd1D
#define I_sceCdSendSCmd1D DECLARE_IMPORT(116, sceCdSendSCmd1D)
Definition at line 313 of file cdvdman.h.
I_sceRemote2_7
#define I_sceRemote2_7 DECLARE_IMPORT(117, sceRemote2_7)
Definition at line 314 of file cdvdman.h.
I_sceCdSetLEDsMode
#define I_sceCdSetLEDsMode DECLARE_IMPORT(120, sceCdSetLEDsMode)
Definition at line 315 of file cdvdman.h.
I_sceCdApplySCmd3
#define I_sceCdApplySCmd3 DECLARE_IMPORT(125, sceCdApplySCmd3)
Definition at line 316 of file cdvdman.h.
I_sceRemote2_7Get
#define I_sceRemote2_7Get DECLARE_IMPORT(128, sceRemote2_7Get)
Definition at line 317 of file cdvdman.h.
I_sceCdReadPS1BootParam
#define I_sceCdReadPS1BootParam DECLARE_IMPORT(148, sceCdReadPS1BootParam)
Definition at line 318 of file cdvdman.h.
I_sceCdSetFanProfile
#define I_sceCdSetFanProfile DECLARE_IMPORT(150, sceCdSetFanProfile)
Definition at line 319 of file cdvdman.h.
I_cdvdman_152_get_temperature
#define I_cdvdman_152_get_temperature DECLARE_IMPORT(152, cdvdman_152_get_temperature)
Definition at line 320 of file cdvdman.h.
I_sceCdChgSys
#define I_sceCdChgSys DECLARE_IMPORT(154, sceCdChgSys)
Definition at line 321 of file cdvdman.h.
I_sceCdNoticeGameStart
#define I_sceCdNoticeGameStart DECLARE_IMPORT(156, sceCdNoticeGameStart)
Definition at line 322 of file cdvdman.h.
I_sceCdDeobfuscateUsingUniqueKey
#define I_sceCdDeobfuscateUsingUniqueKey DECLARE_IMPORT(161, sceCdDeobfuscateUsingUniqueKey)
Definition at line 323 of file cdvdman.h.
I_sceCdXLEDCtl
#define I_sceCdXLEDCtl DECLARE_IMPORT(163, sceCdXLEDCtl)
Definition at line 324 of file cdvdman.h.
I_sceCdBuzzerCtl
#define I_sceCdBuzzerCtl DECLARE_IMPORT(165, sceCdBuzzerCtl)
Definition at line 325 of file cdvdman.h.
I_cdvdman_167_atapi2dragon
#define I_cdvdman_167_atapi2dragon DECLARE_IMPORT(167, cdvdman_167_atapi2dragon)
Definition at line 326 of file cdvdman.h.
I_cdvdman_169_dragon2atapi
#define I_cdvdman_169_dragon2atapi DECLARE_IMPORT(169, cdvdman_169_dragon2atapi)
Definition at line 327 of file cdvdman.h.
I_sceCdXBSPowerCtl
#define I_sceCdXBSPowerCtl DECLARE_IMPORT(171, sceCdXBSPowerCtl)
Definition at line 328 of file cdvdman.h.
I_sceCdSetAtapiEjectCallback
#define I_sceCdSetAtapiEjectCallback DECLARE_IMPORT(173, sceCdSetAtapiEjectCallback)
Definition at line 329 of file cdvdman.h.
I_sceCdSetMediumRemoval
#define I_sceCdSetMediumRemoval DECLARE_IMPORT(175, sceCdSetMediumRemoval)
Definition at line 330 of file cdvdman.h.
I_sceCdGetMediumRemoval
#define I_sceCdGetMediumRemoval DECLARE_IMPORT(177, sceCdGetMediumRemoval)
Definition at line 331 of file cdvdman.h.
I_sceCdDoesUniqueKeyExist
#define I_sceCdDoesUniqueKeyExist DECLARE_IMPORT(179, sceCdDoesUniqueKeyExist)
Definition at line 332 of file cdvdman.h.
I_sceCdXDVRPReset
#define I_sceCdXDVRPReset DECLARE_IMPORT(181, sceCdXDVRPReset)
Definition at line 333 of file cdvdman.h.
I_sceCdGetWakeUpReason
#define I_sceCdGetWakeUpReason DECLARE_IMPORT(183, sceCdGetWakeUpReason)
Definition at line 334 of file cdvdman.h.
I_sceCdReadRegionParams
#define I_sceCdReadRegionParams DECLARE_IMPORT(189, sceCdReadRegionParams)
Definition at line 335 of file cdvdman.h.
I_sceCdWriteRegionParams
#define I_sceCdWriteRegionParams DECLARE_IMPORT(191, sceCdWriteRegionParams)
Definition at line 336 of file cdvdman.h.
Function Documentation
sceCdCheckCmd()
int sceCdCheckCmd (void) extern
Definition at line 6102 of file cdvdman.c.
sceCdNop()
int sceCdNop (void) extern
Definition at line 6182 of file cdvdman.c.
sceGetFsvRbuf()
void * sceGetFsvRbuf (void) extern
Definition at line 406 of file cdvdman.c.
sceCdstm0Cb()
int sceCdstm0Cb (void(* p)(int val)) extern
Definition at line 3910 of file cdvdman.c.
sceCdstm1Cb()
int sceCdstm1Cb (void(* p)(int val)) extern
Definition at line 3916 of file cdvdman.c.
sceCdSC()
int sceCdSC (int code, int * param) extern
Definition at line 4613 of file cdvdman.c.
sceCdRC()
int sceCdRC (sceCdCLOCK * clock) extern
Definition at line 7974 of file cdvdman.c.
sceCdRead0()
int sceCdRead0 (u32 lsn, u32 sectors, void * buffer, sceCdRMode * mode, int csec, void * callback) extern
Definition at line 6568 of file cdvdman.c.
sceCdRV()
int sceCdRV (u32 lsn, u32 sectors, void * buf, sceCdRMode * mode, int arg5, void * cb) extern
Reads DVD video. SUPPORTED IN NEWER CDVDMAN MODULES WITHIN DVD PLAYER IOPRP ONLY
Returns
1 on success, 0 on failure.
Definition at line 7139 of file cdvdman.c.
References sceCdGetDiskType(), SCECdPS2DVD, and sceCdRV().
Referenced by sceCdRV().
sceCdApplySCmd2()
int sceCdApplySCmd2 (u8 cmdNum, const void * inBuff, unsigned long int inBuffSize, void * outBuff) extern
send an s-command by function number
Parameters
cmdNum command number
inBuff input buffer (can be null)
inBuffSize size of input buffer (>= 16 bytes)
outBuff output buffer (can be null)
Returns
1 on success, 0 on failure.
Definition at line 5453 of file cdvdman.c.
References sceCdApplySCmd(), and sceCdApplySCmd2().
Referenced by sceCdApplySCmd2().
sceCdApplySCmd3()
int sceCdApplySCmd3 (u8 cmdNum, const void * inBuff, unsigned long int inBuffSize, void * outBuff) extern
send an s-command by function number Unofficial name. SUPPORTED IN NEWER CDVDMAN MODULES INCLUDED WITHIN NEWER IOPRP ONLY
Parameters
cmdNum command number
inBuff input buffer (can be null)
inBuffSize size of input buffer (>= 16 bytes)
outBuff output buffer (can be null)
Returns
1 on success, 0 on failure.
sceCdSpinCtrlIOP()
int sceCdSpinCtrlIOP (u32 speed) extern
Controls spindle speed? Not sure what it really does. SUPPORTED IN XCDVDMAN ONLY
Parameters
speed Speed mode.
Returns
1 on success, 0 on failure.
Definition at line 2195 of file cdvdman.c.
References sceCdSpinCtrlIOP().
Referenced by sceCdSpinCtrlIOP().
sceCdSetAtapiEjectCallback()
void * sceCdSetAtapiEjectCallback (int(* cb)(int reason, void *userdata), void * userdata) extern
Set the eject callback when in ATAPI mode. Unofficial name. SUPPORTED IN NEWER CDVDMAN MODULES INCLUDED WITHIN DNAS IOPRP ONLY
Parameters
cb The pointer to the callback
userdata The pointer to the userdata that will be passed to the callback
Returns
The old callback value
sceCdReadDiskID()
int sceCdReadDiskID (unsigned int * id) extern
Reads the Disk ID. SUPPORTED IN NEWER CDVDMAN MODULES INCLUDED WITHIN DNAS IOPRP ONLY
Parameters
id integer where the Disk ID is stored.
Returns
1 on success, 0 on failure.
sceCdDeobfuscateUsingUniqueKey()
int sceCdDeobfuscateUsingUniqueKey (u8 * buffer, unsigned int shiftval, int xorval, u32 * status) extern
Deobfuscate using unique key. Unofficial name. SUPPORTED IN NEWER CDVDMAN MODULES INCLUDED WITHIN DNAS IOPRP ONLY
Parameters
buffer Output buffer
shiftval The amount to rotate left shift
xorval The value to XOR the buffer against
status Command status
Returns
1 on success, 0 on failure.