PS2SDK: ee/draw/include/draw_blending.h File Reference
draw_blending.h File Reference
#include <tamtypes.h>
Data Structures
struct blend_t
Macros
#define BLEND_COLOR_SOURCE 0
#define BLEND_COLOR_DEST 1
#define BLEND_COLOR_ZERO 2
#define BLEND_ALPHA_SOURCE 0
#define BLEND_ALPHA_DEST 1
#define BLEND_ALPHA_FIXED 2
#define ALPHA_CORRECT_RGBA32 0
#define ALPHA_CORRECT_RGBA16 1
Functions
qword_t * draw_pixel_alpha_control (qword_t *q, int enable)
qword_t * draw_alpha_blending (qword_t *q, int context, blend_t *blend)
qword_t * draw_alpha_correction (qword_t *q, int context, int alpha)
Detailed Description
Draw library blending functions
Definition in file draw_blending.h.
Data Structure Documentation
blend_t
struct blend_t
Definition at line 26 of file draw_blending.h.
Data Fields
char color1
char color2
char alpha
char color3
unsigned char fixed_alpha
Macro Definition Documentation
BLEND_COLOR_SOURCE
#define BLEND_COLOR_SOURCE 0
Alpha Blending
Definition at line 14 of file draw_blending.h.
Referenced by draw_setup_environment().
BLEND_COLOR_DEST
#define BLEND_COLOR_DEST 1
Definition at line 15 of file draw_blending.h.
BLEND_COLOR_ZERO
#define BLEND_COLOR_ZERO 2
Definition at line 16 of file draw_blending.h.
BLEND_ALPHA_SOURCE
#define BLEND_ALPHA_SOURCE 0
Definition at line 18 of file draw_blending.h.
BLEND_ALPHA_DEST
#define BLEND_ALPHA_DEST 1
Definition at line 19 of file draw_blending.h.
BLEND_ALPHA_FIXED
#define BLEND_ALPHA_FIXED 2
Definition at line 20 of file draw_blending.h.
ALPHA_CORRECT_RGBA32
#define ALPHA_CORRECT_RGBA32 0
Alpha Correction
Definition at line 23 of file draw_blending.h.
Referenced by draw_setup_environment().
ALPHA_CORRECT_RGBA16
#define ALPHA_CORRECT_RGBA16 1
Definition at line 24 of file draw_blending.h.
Function Documentation
draw_pixel_alpha_control()
qword_t * draw_pixel_alpha_control (qword_t * q, int enable) extern
Alpha Blending Per-Pixel MSB Control
Definition at line 8 of file draw_environment.c.
References draw_pixel_alpha_control(), GIF_FLG_PACKED, GIF_REG_AD, and GS_REG_PABE.
Referenced by draw_pixel_alpha_control().
draw_alpha_blending()
qword_t * draw_alpha_blending (qword_t * q, int context, blend_t * blend) extern
Alpha Blending
Definition at line 20 of file draw_environment.c.
References draw_alpha_blending(), GIF_FLG_PACKED, GIF_REG_AD, and GS_REG_ALPHA.
Referenced by draw_alpha_blending().
draw_alpha_correction()
qword_t * draw_alpha_correction (qword_t * q, int context, int alpha) extern
Alpha Correction
Definition at line 176 of file draw_environment.c.
References draw_alpha_correction(), GIF_FLG_PACKED, GIF_REG_AD, and GS_REG_FBA.
Referenced by draw_alpha_correction().