PS2SDK: ee/draw/include/draw_masking.h File Reference
draw_masking.h File Reference
#include <tamtypes.h>
Macros
#define SCAN_MASK_NORMAL 0
#define SCAN_MASK_ODD 2
#define SCAN_MASK_EVEN 3
#define COLOR_CLAMP_MASK 0
#define COLOR_CLAMP_ENABLE 1
Functions
qword_t * draw_scan_masking (qword_t *q, int mask)
qword_t * draw_color_clamping (qword_t *q, int enable)
Detailed Description
Draw library masking functions
Definition in file draw_masking.h.
Macro Definition Documentation
SCAN_MASK_NORMAL
#define SCAN_MASK_NORMAL 0
Scan masking
Definition at line 12 of file draw_masking.h.
SCAN_MASK_ODD
#define SCAN_MASK_ODD 2
Definition at line 13 of file draw_masking.h.
SCAN_MASK_EVEN
#define SCAN_MASK_EVEN 3
Definition at line 14 of file draw_masking.h.
COLOR_CLAMP_MASK
#define COLOR_CLAMP_MASK 0
Color Clamping
Definition at line 17 of file draw_masking.h.
COLOR_CLAMP_ENABLE
#define COLOR_CLAMP_ENABLE 1
Definition at line 18 of file draw_masking.h.
Function Documentation
draw_scan_masking()
qword_t * draw_scan_masking (qword_t * q, int mask) extern
Scanline Masking (framebuffer)
Definition at line 150 of file draw_environment.c.
References draw_scan_masking(), GIF_FLG_PACKED, GIF_REG_AD, and GS_REG_SCANMSK.
Referenced by draw_scan_masking().
draw_color_clamping()
qword_t * draw_color_clamping (qword_t * q, int enable) extern
Color Masking/Clamping
Definition at line 163 of file draw_environment.c.
References draw_color_clamping(), GIF_FLG_PACKED, GIF_REG_AD, and GS_REG_COLCLAMP.
Referenced by draw_color_clamping().