PS2SDK: ee/sbv/src/slib.c File Reference
slib.c File Reference
#include <tamtypes.h>
#include <kernel.h>
#include <string.h>
#include <sifrpc.h>
#include "slib.h"
#include "smod.h"
#include "common.h"
Macros
#define EXP_LIB_MAX SMEM_BUF_SIZE /* We can even handle CDVDMAN's bloat! */
Functions
slib_exp_lib_list_t * slib_exp_lib_list (void)
int slib_get_exp_lib (const char *name, slib_exp_lib_t *library)
Variables
slib_exp_lib_list_t _slib_cur_exp_lib_list = {NULL, NULL}
struct smem_buf smem_buf
Detailed Description
Sub CPU library interface.
Definition in file slib.c.
Macro Definition Documentation
EXP_LIB_MAX
#define EXP_LIB_MAX SMEM_BUF_SIZE /* We can even handle CDVDMAN's bloat! */
Definition at line 101 of file slib.c.
Function Documentation
slib_exp_lib_list()
slib_exp_lib_list_t * slib_exp_lib_list ()
Find the head and tail of the export library list.
Returns
NULL if the list couldn't be found, and the address of the head and tail pointers if it was located.
This routine will need to be called everytime the IOP is reset.
Definition at line 31 of file slib.c.
Referenced by slib_get_exp_lib().
slib_get_exp_lib()
int slib_get_exp_lib (const char * name, slib_exp_lib_t * library)
Retrieve an export library by name.
Definition at line 103 of file slib.c.
References count, and slib_exp_lib_list().
Referenced by sbv_patch_disable_prefix_check(), and sbv_patch_enable_lmb().
Variable Documentation
_slib_cur_exp_lib_list
slib_exp_lib_list_t _slib_cur_exp_lib_list = {NULL, NULL}
Definition at line 26 of file slib.c.