PS2SDK: ee/sbv/src/smod.c File Reference
smod.c File Reference
#include <tamtypes.h>
#include <kernel.h>
#include <string.h>
#include <sifrpc.h>
#include "smem.h"
#include "slib.h"
#include "smod.h"
#include "common.h"
Functions
int smod_get_next_mod (smod_mod_info_t *cur_mod, smod_mod_info_t *next_mod)
int smod_get_mod_by_name (const char *name, smod_mod_info_t *info)
Variables
struct smem_buf smem_buf
Detailed Description
Sub-CPU module interface.
Definition in file smod.c.
Function Documentation
smod_get_next_mod()
int smod_get_next_mod (smod_mod_info_t * cur_mod, smod_mod_info_t * next_mod)
Return the next module referenced in the global module list.
Definition at line 30 of file smod.c.
Referenced by list_all_modules(), smod_get_mod_by_name(), smod_get_mod_by_name(), and smod_get_modcount_by_name().
smod_get_mod_by_name()
int smod_get_mod_by_name (const char * name, smod_mod_info_t * info)
Find and retreive a module by it's module name.
Definition at line 54 of file smod.c.
References smod_get_next_mod().
Referenced by iopmgr_get_devicelist(), iopmgr_get_iomandev(), iopmgr_get_iomanxdev(), list_devices_ioman(), list_devices_iomanx(), sbv_patch_enable_lmb(), sbv_patch_fileio(), and smod_get_modversion_by_name().