var file_xio_8h =
[
    [ "rests_pkt", "ps2ip__rpc_8h.html#structrests__pkt", null ],
    [ "fileXioDirEntry", "file_xio_8h.html#structfile_xio_dir_entry", null ],
    [ "fileXioDevice", "file_xio_8h.html#structfile_xio_device", [
      [ "version", "file_xio_8h.html#a805261445f6db2ffc8b8dd6390b6bf3b", null ]
    ] ],
    [ "fxio_devlist_packet", "file_xio_8h.html#structfxio__devlist__packet", null ],
    [ "fxio_getdir_packet", "file_xio_8h.html#structfxio__getdir__packet", null ],
    [ "fxio_mount_packet", "file_xio_8h.html#structfxio__mount__packet", null ],
    [ "fxio_unmount_packet", "file_xio_8h.html#structfxio__unmount__packet", null ],
    [ "fxio_copyfile_packet", "file_xio_8h.html#structfxio__copyfile__packet", null ],
    [ "fxio_mkdir_packet", "file_xio_8h.html#structfxio__mkdir__packet", null ],
    [ "fxio_pathsel_packet", "file_xio_8h.html#structfxio__pathsel__packet", null ],
    [ "fxio_rename_packet", "file_xio_8h.html#structfxio__rename__packet", null ],
    [ "fxio_readlink_packet", "file_xio_8h.html#structfxio__readlink__packet", null ],
    [ "fxio_open_packet", "file_xio_8h.html#structfxio__open__packet", null ],
    [ "fxio_close_packet", "file_xio_8h.html#structfxio__close__packet", null ],
    [ "fxio_read_packet", "file_xio_8h.html#structfxio__read__packet", null ],
    [ "fxio_write_packet", "file_xio_8h.html#structfxio__write__packet", null ],
    [ "fxio_lseek_packet", "file_xio_8h.html#structfxio__lseek__packet", null ],
    [ "fxio_lseek64_packet", "file_xio_8h.html#structfxio__lseek64__packet", null ],
    [ "fxio_chstat_packet", "file_xio_8h.html#structfxio__chstat__packet", null ],
    [ "fxio_getstat_packet", "file_xio_8h.html#structfxio__getstat__packet", null ],
    [ "fxio_format_packet", "file_xio_8h.html#structfxio__format__packet", null ],
    [ "fxio_sync_packet", "file_xio_8h.html#structfxio__sync__packet", null ],
    [ "fxio_dread_packet", "file_xio_8h.html#structfxio__dread__packet", null ],
    [ "fxio_devctl_packet", "file_xio_8h.html#structfxio__devctl__packet", null ],
    [ "fxio_ioctl_packet", "file_xio_8h.html#structfxio__ioctl__packet", null ],
    [ "fxio_ioctl2_packet", "file_xio_8h.html#structfxio__ioctl2__packet", null ],
    [ "fxio_ctl_return_pkt", "file_xio_8h.html#structfxio__ctl__return__pkt", null ],
    [ "fxio_lseek64_return_pkt", "file_xio_8h.html#structfxio__lseek64__return__pkt", null ],
    [ "fxio_rwbuff", "file_xio_8h.html#structfxio__rwbuff", null ],
    [ "FILEXIO_DT_FSEXT", "file_xio_8h.html#a0e4050cc22850567ed8274f634b656a2", null ],
    [ "version", "file_xio_8h.html#a5408ac5df4c170828874e1b10b4c35a0", null ]
];