PS2SDK: ee/graph/include/graph_config.h File Reference
graph_config.h File Reference
Functions
int graph_make_config (int mode, int interlace, int ffmd, int x, int y, int flicker_filter, char *config)
int graph_get_config (char *config)
int graph_set_config (char *config)
int graph_load_config (char *filename)
int graph_save_config (char *filename)
Detailed Description
Graph library config
Definition in file graph_config.h.
Function Documentation
graph_make_config()
int graph_make_config (int mode, int interlace, int ffmd, int x, int y, int flicker_filter, char * config) extern
Creates a string from the current mode. The string format is: mode:int:ffmd:filter:x:y:
Definition at line 8 of file graph_config.c.
References GRAPH_DISABLE, graph_make_config(), GRAPH_MODE_HDTV_1080I, GRAPH_MODE_HDTV_480P, GRAPH_MODE_HDTV_576P, GRAPH_MODE_HDTV_720P, GRAPH_MODE_NTSC, GRAPH_MODE_PAL, GRAPH_MODE_VGA_1024_60, GRAPH_MODE_VGA_1024_70, GRAPH_MODE_VGA_1024_75, GRAPH_MODE_VGA_1024_85, GRAPH_MODE_VGA_1280_60, GRAPH_MODE_VGA_1280_75, GRAPH_MODE_VGA_640_60, GRAPH_MODE_VGA_640_72, GRAPH_MODE_VGA_640_75, GRAPH_MODE_VGA_640_85, GRAPH_MODE_VGA_800_56, GRAPH_MODE_VGA_800_60, GRAPH_MODE_VGA_800_72, GRAPH_MODE_VGA_800_75, and GRAPH_MODE_VGA_800_85.
Referenced by graph_get_config(), and graph_make_config().
graph_get_config()
int graph_get_config (char * config) extern
Gets the string made from the current mode.
Definition at line 424 of file graph_mode.c.
References graph_get_config(), and graph_make_config().
Referenced by graph_get_config(), and graph_save_config().
graph_set_config()
int graph_set_config (char * config) extern
Sets the mode from the configuration string.
Definition at line 79 of file graph_config.c.
References GRAPH_DISABLE, GRAPH_MODE_AUTO, GRAPH_MODE_HDTV_1080I, GRAPH_MODE_HDTV_480P, GRAPH_MODE_HDTV_576P, GRAPH_MODE_HDTV_720P, GRAPH_MODE_NTSC, GRAPH_MODE_PAL, GRAPH_MODE_VGA_1024_60, GRAPH_MODE_VGA_1024_70, GRAPH_MODE_VGA_1024_75, GRAPH_MODE_VGA_1024_85, GRAPH_MODE_VGA_1280_60, GRAPH_MODE_VGA_1280_75, GRAPH_MODE_VGA_640_60, GRAPH_MODE_VGA_640_72, GRAPH_MODE_VGA_640_75, GRAPH_MODE_VGA_640_85, GRAPH_MODE_VGA_800_56, GRAPH_MODE_VGA_800_60, GRAPH_MODE_VGA_800_72, GRAPH_MODE_VGA_800_75, GRAPH_MODE_VGA_800_85, graph_set_config(), and graph_set_mode().
Referenced by graph_load_config(), and graph_set_config().
graph_load_config()
int graph_load_config (char * filename) extern
Reads the configuration string from a file and sets it.
Definition at line 184 of file graph_config.c.
References EIO, ENOENT, graph_load_config(), and graph_set_config().
Referenced by graph_load_config().
graph_save_config()
int graph_save_config (char * filename) extern
Writes the current mode information into a config file as a string.
Definition at line 219 of file graph_config.c.
References EIO, ENOENT, graph_get_config(), and graph_save_config().
Referenced by graph_save_config().