PS2SDK: iop/sound/audsrv/src/rpc_server.c File Reference
rpc_server.c File Reference
#include <stdio.h>
#include <thbase.h>
#include <thsemap.h>
#include <loadcore.h>
#include <sysmem.h>
#include <intrman.h>
#include <sifcmd.h>
#include <audsrv.h>
#include "audsrv_internal.h"
#include "common.h"
#include "rpc_client.h"
#include "debug_printf.h"
Functions
static int rpc_buffer[18000/4] __attribute__ ((__aligned__(4)))
static void * rpc_command (int func, unsigned *data, int size)
static void rpc_server_thread (void *arg)
int initialize_rpc_thread ()
Variables
static SifRpcDataQueue_t qd
static SifRpcServerData_t sd0
Detailed Description
audsrv iop rpc server.
Definition in file rpc_server.c.
Function Documentation
__attribute__()
static int rpc_buffer[18000/4] __attribute__ ((__aligned__(4))) static
buffer for RPC DMA
rpc_command()
static void * rpc_command (int func, unsigned * data, int size) static
RPC command handler.
Parameters
func command (one of AUDSRV_x)
data pointer to data array
size size of data array (in bytes)
Returns
value depends on function invoked
This is a single rpc handler, it unpacks the data array and calls local functions.
Definition at line 47 of file rpc_server.c.
References audsrv_adpcm_init(), audsrv_available(), audsrv_cd_pause(), audsrv_cd_play_sectors(), audsrv_cd_resume(), audsrv_ch_play_adpcm(), AUDSRV_FORMAT_OK, audsrv_format_ok(), audsrv_get_cd_status(), audsrv_get_cd_type(), audsrv_get_cdpos(), audsrv_get_numtracks(), audsrv_get_track_offset(), audsrv_get_trackpos(), AUDSRV_INIT, audsrv_init(), AUDSRV_INIT_ADPCM, audsrv_is_adpcm_playing(), audsrv_load_adpcm(), audsrv_play_audio(), AUDSRV_PLAY_CD, audsrv_play_cd(), audsrv_queued(), audsrv_quit(), audsrv_set_format(), audsrv_set_volume(), audsrv_stop_audio(), audsrv_stop_cd(), audsrv_wait_audio(), and free_sample().
Referenced by rpc_server_thread().
rpc_server_thread()
static void rpc_server_thread (void * arg) static
RPC listener thread
Parameters
arg not used
This is the main RPC thread. Nothing fancy here.
Definition at line 182 of file rpc_server.c.
References qd, rpc_command(), and sd0.
initialize_rpc_thread()
int initialize_rpc_thread ()
Definition at line 195 of file rpc_server.c.
Variable Documentation
qd
SifRpcDataQueue_t qd static
RPC thread variables
Definition at line 33 of file rpc_server.c.
Referenced by rpc_server_thread().
sd0
SifRpcServerData_t sd0 static
RPC thread variables
Definition at line 35 of file rpc_server.c.
Referenced by rpc_server_thread().