PS2SDK: ee/sbv/include/slib.h File Reference
slib.h File Reference
#include <tamtypes.h>
Data Structures
struct _slib_imp_list
struct _slib_exp_lib
struct _slib_exp_lib_list
Typedefs
typedef struct _slib_imp_list slib_imp_list_t
typedef struct _slib_exp_lib slib_exp_lib_t
typedef struct _slib_exp_lib_list slib_exp_lib_list_t
Functions
slib_exp_lib_list_t * slib_exp_lib_list ()
int slib_get_exp_lib (const char *name, slib_exp_lib_t *library)
Detailed Description
Sub-CPU library interface.
Definition in file slib.h.
Data Structure Documentation
_slib_imp_list
struct _slib_imp_list
Describes an IRX import list.
Definition at line 22 of file slib.h.
Data Fields
u8 magic
struct _slib_imp_list * next
u16 version
u16 flags
u8 name[8]
void * imports[]
_slib_exp_lib
struct _slib_exp_lib
Describes an IRX export library.
Definition at line 32 of file slib.h.
Data Fields
struct _slib_exp_lib * prev
struct _slib_imp_list * caller
u16 version
u16 flags
u8 name[8]
void * exports[]
_slib_exp_lib_list
struct _slib_exp_lib_list
The LOADCORE library has a routine that returns a pointer to the following structure. It keeps track of all libraries added to the system with RegisterLibraryEntries().
Definition at line 45 of file slib.h.
Data Fields
struct _slib_exp_lib * tail
struct _slib_exp_lib * head
Typedef Documentation
slib_imp_list_t
typedef struct _slib_imp_list slib_imp_list_t
Describes an IRX import list.
slib_exp_lib_t
typedef struct _slib_exp_lib slib_exp_lib_t
Describes an IRX export library.
slib_exp_lib_list_t
typedef struct _slib_exp_lib_list slib_exp_lib_list_t
The LOADCORE library has a routine that returns a pointer to the following structure. It keeps track of all libraries added to the system with RegisterLibraryEntries().
Function Documentation
slib_exp_lib_list()
slib_exp_lib_list_t * slib_exp_lib_list () extern
Find the head and tail of the export library list.
Returns
NULL if the list couldn't be found, and the address of the head and tail pointers if it was located.
This routine will need to be called everytime the IOP is reset.
Definition at line 31 of file slib.c.
Referenced by slib_get_exp_lib().
slib_get_exp_lib()
int slib_get_exp_lib (const char * name, slib_exp_lib_t * library) extern
Retrieve an export library by name.
Definition at line 103 of file slib.c.
References count, and slib_exp_lib_list().
Referenced by sbv_patch_disable_prefix_check(), and sbv_patch_enable_lmb().