PS2SDK: ee/sbv/include/smod.h File Reference
smod.h File Reference
#include <tamtypes.h>
Data Structures
struct _smod_mod_info
Typedefs
typedef struct _smod_mod_info smod_mod_info_t
Functions
int smod_get_next_mod (smod_mod_info_t *cur_mod, smod_mod_info_t *next_mod)
int smod_get_mod_by_name (const char *name, smod_mod_info_t *info)
Detailed Description
Sub-CPU module interface.
Definition in file smod.h.
Data Structure Documentation
_smod_mod_info
struct _smod_mod_info
Module info entry.
Most of the fields are self-explanatory. I don't know what the *flags fields do, and they don't seem to be important.
Definition at line 24 of file smod.h.
Data Fields
struct _smod_mod_info * next
char * name
A pointer to the name in IOP RAM, this must be smem_read().
u16 version
u16 newflags
For MODLOAD shipped with games. The old MODLOAD module from boot ROMs do not use a flags field.
u16 id
u16 unused
u32 entry
_start
u32 gp
u32 text_start
u32 text_size
u32 data_size
u32 bss_size
u32 unused1
u32 unused2
Typedef Documentation
smod_mod_info_t
typedef struct _smod_mod_info smod_mod_info_t
Module info entry.
Most of the fields are self-explanatory. I don't know what the *flags fields do, and they don't seem to be important.
Function Documentation
smod_get_next_mod()
int smod_get_next_mod (smod_mod_info_t * cur_mod, smod_mod_info_t * next_mod) extern
Return the next module referenced in the global module list.
Definition at line 30 of file smod.c.
Referenced by list_all_modules(), smod_get_mod_by_name(), smod_get_mod_by_name(), and smod_get_modcount_by_name().
smod_get_mod_by_name()
int smod_get_mod_by_name (const char * name, smod_mod_info_t * info) extern
Find and retreive a module by it's module name.
Definition at line 54 of file smod.c.
References smod_get_next_mod().
Referenced by iopmgr_get_devicelist(), iopmgr_get_iomandev(), iopmgr_get_iomanxdev(), list_devices_ioman(), list_devices_iomanx(), sbv_patch_enable_lmb(), sbv_patch_fileio(), and smod_get_modversion_by_name().