var searchData=
[
  ['uart16550_5fregs_5f_5483',['uart16550_regs_',['../structuart16550__regs__.html',1,'']]],
  ['uart_5fbuf_5484',['uart_buf',['../structuart__buf.html',1,'']]],
  ['uart_5fsoftc_5485',['uart_softc',['../structuart__softc.html',1,'']]],
  ['upsample_5ft_5486',['upsample_t',['../upsamplers_8h.html#structupsample__t',1,'']]],
  ['usb_5fmmio_5fhwport_5f_5487',['usb_mmio_hwport_',['../iop__mmio__hwport_8h.html#structusb__mmio__hwport__',1,'']]],
  ['usbconfigdescriptor_5488',['UsbConfigDescriptor',['../usbd_8h.html#struct_usb_config_descriptor',1,'']]],
  ['usbdevicedescriptor_5489',['UsbDeviceDescriptor',['../usbd_8h.html#struct_usb_device_descriptor',1,'']]],
  ['usbdevicerequest_5490',['UsbDeviceRequest',['../usbd_8h.html#struct_usb_device_request',1,'']]],
  ['usbendpointdescriptor_5491',['UsbEndpointDescriptor',['../usbd_8h.html#struct_usb_endpoint_descriptor',1,'']]],
  ['usbhubdescriptor_5492',['UsbHubDescriptor',['../usbd_8h.html#struct_usb_hub_descriptor',1,'']]],
  ['usbinterfacedescriptor_5493',['UsbInterfaceDescriptor',['../usbd_8h.html#struct_usb_interface_descriptor',1,'']]],
  ['usbm_5fload_5fentry_5494',['usbm_load_entry',['../structusbm__load__entry.html',1,'']]],
  ['usbmass_5fcmd_5495',['usbmass_cmd',['../structusbmass__cmd.html',1,'']]],
  ['usbmassdeviceinfo_5496',['UsbMassDeviceInfo',['../usbhdfsd_8h.html#struct_usb_mass_device_info',1,'']]],
  ['usbstringdescriptor_5497',['UsbStringDescriptor',['../usbd_8h.html#struct_usb_string_descriptor',1,'']]],
  ['utimbuf_5498',['utimbuf',['../structutimbuf.html',1,'']]]
];
