# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

EE_SRC_DIR = $(PS2SDKSRC)/ee/elf-loader/src/loader/src/
EE_INC_DIR = $(PS2SDKSRC)/ee/elf-loader/src/loader/include/

LOADER_ENABLE_DEBUG_COLORS ?= 0

EE_LINKFILE ?= $(PS2SDKSRC)/ee/elf-loader/src/loader/linkfile

EE_BIN ?= loader.elf

include $(PS2SDKSRC)/ee/elf-loader/src/loader/Makefile
