# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_SRC_DIR = $(PS2SDKSRC)/iop/dev9/atad/src/
IOP_INC_DIR = $(PS2SDKSRC)/iop/dev9/atad/include/

ATA_ENABLE_BDM ?= 1

IOP_BIN ?= ata_bd.irx

include $(PS2SDKSRC)/iop/dev9/atad/Makefile
