# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

SUBDIRS = \
    mtapman \
    mtapman-1400 \
    mx4sio_bd \
    mx4sio_bd_mini \
    sio2log \
    sio2man \
    sio2man-nano

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make
