# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_SRC_DIR = $(PS2SDKSRC)/iop/sio/mx4sio_bd/src/

IOP_OBJS += xprintf.o rpc_printf.o

IOP_CFLAGS += -DDEBUG -DRPC_PRINTF

include $(PS2SDKSRC)/iop/sio/mx4sio_bd/Makefile
