#!/bin/sh

# bin2o (heh)
# script to convert a binary data to an elf object file
# (c)2000 Dan Potter
# $Id$

if [ $# != 3 ]; then
	echo usage: $0 \<input file\> \<symbol\> \<output file\>
	exit 0
fi

echo "OUTPUT_ARCH(mips:5900) SECTIONS { .rodata : { $2 = .; *(.data); $2_end = .; } }" > /tmp/script.ld
ee-ld --no-warn-mismatch --format binary --oformat elf64-littlemips -mips3 $1 -o $3 -r -EL -T /tmp/script.ld

rm -f /tmp/script.ld
