# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_PARENT_DIR = $(PS2SDKSRC)/iop/security/secrman
IOP_SRC_DIR = $(IOP_PARENT_DIR)/src/
IOP_INC_DIR = $(IOP_PARENT_DIR)/include/

IOP_BIN = secrman_arcade.irx

BUILDING_ARCADE_SECRMAN = 1
DEX_SUPPORT = 0
IOP_CFLAGS += -DBUILDING_ARCADE_SECRMAN

include $(IOP_PARENT_DIR)/Makefile
