IOP_PARENT_DIR = $(PS2SDKSRC)/iop/security/secrman
IOP_SRC_DIR = $(IOP_PARENT_DIR)/src/
IOP_INC_DIR = $(IOP_PARENT_DIR)/include/

IOP_BIN ?= secrman_arcade_namco.irx

COH_SUPPORT ?= 1

include $(IOP_PARENT_DIR)/Makefile