# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2024, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_PARENT_DIR = $(PS2SDKSRC)/iop/arcade/acuart
IOP_SRC_DIR = $(IOP_PARENT_DIR)/src/
IOP_INC_DIR = $(IOP_PARENT_DIR)/include/

ADD_TTY = 1

IOP_BIN ?= acuart_tty.irx

include $(IOP_PARENT_DIR)/Makefile
