# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

SUBDIRS = \
	acata \
	acatad \
	accdvd \
	accdvde \
	accore \
	acdev \
	acdev9 \
	acflash \
	acfpgald \
	acjv \
	acjvld \
	acmem \
	acmeme \
	acram \
	acrtc \
	acsram \
	actimer \
	acuart \
	acuart_tty

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make
