/*
# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright (c) 2006-2007 Eugene Plotnikov <e-plotnikov@operamail.com>
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.
*/

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_block_fr" "\n"
	"\t" ".ent _MPEG_put_block_fr" "\n"
	"\t" "_MPEG_put_block_fr:" "\n"
	"\t" "\t" "lw      $a2, 0($a0)" "\n"
	"\t" "\t" "lw      $a3, 8($a0)" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "addiu   $v1, $zero, 6" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 8" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $a4,   0($a3)" "\n"
	"\t" "\t" "lq      $a5,  16($a3)" "\n"
	"\t" "\t" "lq      $a6,  32($a3)" "\n"
	"\t" "\t" "lq      $a7,  48($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1;" "\n"
	"\t" "\t" "lq      $t0,  64($a3)" "\n"
	"\t" "\t" "lq      $t1,  80($a3)" "\n"
	"\t" "\t" "lq      $t2,  96($a3)" "\n"
	"\t" "\t" "lq      $t3, 112($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 128" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $a4,  0($a2)" "\n"
	"\t" "\t" "sq      $a6, 16($a2)" "\n"
	"\t" "\t" "sq      $t0, 32($a2)" "\n"
	"\t" "\t" "sq      $t2, 48($a2)" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_block_fr" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_block_fl" "\n"
	"\t" ".ent _MPEG_put_block_fl" "\n"
	"\t" "_MPEG_put_block_fl:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "lw      $a2, 0($a0)" "\n"
	"\t" "\t" "lw      $a3, 8($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 4" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 8" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $a4,   0($a3)" "\n"
	"\t" "\t" "lq      $a5,  16($a3)" "\n"
	"\t" "\t" "lq      $a6,  32($a3)" "\n"
	"\t" "\t" "lq      $a7,  48($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0, 256($a3)" "\n"
	"\t" "\t" "lq      $t1, 272($a3)" "\n"
	"\t" "\t" "lq      $t2, 288($a3)" "\n"
	"\t" "\t" "lq      $t3, 304($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 64" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $a4,  0($a2)" "\n"
	"\t" "\t" "sq      $t0, 16($a2)" "\n"
	"\t" "\t" "sq      $a6, 32($a2)" "\n"
	"\t" "\t" "sq      $t2, 48($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "addiu   $v1, $v1, 2" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "lq      $a4, 256($a3)" "\n"
	"\t" "\t" "lq      $a5, 272($a3)" "\n"
	"\t" "\t" "lq      $a6, 288($a3)" "\n"
	"\t" "\t" "lq      $a7, 304($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0, 320($a3)" "\n"
	"\t" "\t" "lq      $t1, 336($a3)" "\n"
	"\t" "\t" "lq      $t2, 352($a3)" "\n"
	"\t" "\t" "lq      $t3, 368($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 128" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $a4,  0($a2)" "\n"
	"\t" "\t" "sq      $a6, 16($a2)" "\n"
	"\t" "\t" "sq      $t0, 32($a2)" "\n"
	"\t" "\t" "sq      $t2, 48($a2)" "\n"
	"\t" "\t" "bgtzl   $v1, 2b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_block_fl" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_block_il" "\n"
	"\t" ".ent _MPEG_put_block_il" "\n"
	"\t" "_MPEG_put_block_il:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "lw      $a2,  0($a0)" "\n"
	"\t" "\t" "lw      $a3,  8($a0)" "\n"
	"\t" "\t" "lw      $at, 24($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 4" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 8" "\n"
	"\t" "\t" "addu    $at, $at, $a2" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $a4,   0($a3)" "\n"
	"\t" "\t" "lq      $a5,  16($a3)" "\n"
	"\t" "\t" "lq      $a6,  32($a3)" "\n"
	"\t" "\t" "lq      $a7,  48($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0, 256($a3)" "\n"
	"\t" "\t" "lq      $t1, 272($a3)" "\n"
	"\t" "\t" "lq      $t2, 288($a3)" "\n"
	"\t" "\t" "lq      $t3, 304($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 64" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $a4,  0($a2)" "\n"
	"\t" "\t" "sq      $a6, 32($a2)" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "sq      $t0,  0($at)" "\n"
	"\t" "\t" "sq      $t2, 32($at)" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addiu   $at, $at, 64" "\n"
	"\t" "\t" "lw      $a2,  4($a0)" "\n"
	"\t" "\t" "lw      $at, 24($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 2" "\n"
	"\t" "\t" "addu    $at, $at, $a2" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "lq      $a4, 256($a3)" "\n"
	"\t" "\t" "lq      $a5, 272($a3)" "\n"
	"\t" "\t" "lq      $a6, 288($a3)" "\n"
	"\t" "\t" "lq      $a7, 304($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0, 320($a3)" "\n"
	"\t" "\t" "lq      $t1, 336($a3)" "\n"
	"\t" "\t" "lq      $t2, 352($a3)" "\n"
	"\t" "\t" "lq      $t3, 368($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 128" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $a4, $zero, $a4" "\n"
	"\t" "\t" "ppacb   $a5, $zero, $a5" "\n"
	"\t" "\t" "ppacb   $a6, $zero, $a6" "\n"
	"\t" "\t" "ppacb   $a7, $zero, $a7" "\n"
	"\t" "\t" "ppacb   $t0, $zero, $t0" "\n"
	"\t" "\t" "ppacb   $t1, $zero, $t1" "\n"
	"\t" "\t" "ppacb   $t2, $zero, $t2" "\n"
	"\t" "\t" "ppacb   $t3, $zero, $t3" "\n"
	"\t" "\t" "sd      $a4,  0($a2)" "\n"
	"\t" "\t" "sd      $a5, 16($a2)" "\n"
	"\t" "\t" "sd      $a6, 32($a2)" "\n"
	"\t" "\t" "sd      $a7, 48($a2)" "\n"
	"\t" "\t" "sd      $t0,  0($at)" "\n"
	"\t" "\t" "sd      $t1, 16($at)" "\n"
	"\t" "\t" "sd      $t2, 32($at)" "\n"
	"\t" "\t" "sd      $t3, 48($at)" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "bgtzl   $v1, 2b" "\n"
	"\t" "\t" "addiu   $at, $at, 64" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_block_il" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_add_block_frfr" "\n"
	"\t" ".ent _MPEG_add_block_frfr" "\n"
	"\t" "_MPEG_add_block_frfr:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "lw      $a2,  0($a0)" "\n"
	"\t" "\t" "lw      $a3, 12($a0)" "\n"
	"\t" "\t" "lw      $a0, 16($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 6" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 8" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $a4,   0($a3)" "\n"
	"\t" "\t" "lq      $a5,  16($a3)" "\n"
	"\t" "\t" "lq      $a6,  32($a3)" "\n"
	"\t" "\t" "lq      $a7,  48($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0,   0($a0)" "\n"
	"\t" "\t" "lq      $t1,  16($a0)" "\n"
	"\t" "\t" "lq      $t2,  32($a0)" "\n"
	"\t" "\t" "lq      $t3,  48($a0)" "\n"
	"\t" "\t" "paddh   $a4, $a4, $t0" "\n"
	"\t" "\t" "paddh   $a5, $a5, $t1" "\n"
	"\t" "\t" "paddh   $a6, $a6, $t2" "\n"
	"\t" "\t" "paddh   $a7, $a7, $t3" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "sq      $a4,  0($a2)" "\n"
	"\t" "\t" "sq      $a6, 16($a2)" "\n"
	"\t" "\t" "lq      $t0,  64($a3)" "\n"
	"\t" "\t" "lq      $t1,  80($a3)" "\n"
	"\t" "\t" "lq      $t2,  96($a3)" "\n"
	"\t" "\t" "lq      $t3, 112($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 128" "\n"
	"\t" "\t" "lq      $a4,  64($a0)" "\n"
	"\t" "\t" "lq      $a5,  80($a0)" "\n"
	"\t" "\t" "lq      $a6,  96($a0)" "\n"
	"\t" "\t" "lq      $a7, 112($a0)" "\n"
	"\t" "\t" "addiu   $a0, $a0, 128" "\n"
	"\t" "\t" "paddh   $t0, $t0, $a4" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "paddh   $t3, $t3, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $t0, 32($a2)" "\n"
	"\t" "\t" "sq      $t2, 48($a2)" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_add_block_frfr" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_add_block_ilfl" "\n"
	"\t" ".ent _MPEG_add_block_ilfl" "\n"
	"\t" "_MPEG_add_block_ilfl:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "lw      $a2,  0($a0)" "\n"
	"\t" "\t" "lw      $a3, 12($a0)" "\n"
	"\t" "\t" "lw      $at, 24($a0)" "\n"
	"\t" "\t" "lw      $a1, 16($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 4" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 8" "\n"
	"\t" "\t" "addu    $at, $at, $a2" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $a4,   0($a3)" "\n"
	"\t" "\t" "lq      $a5,  16($a3)" "\n"
	"\t" "\t" "lq      $a6,  32($a3)" "\n"
	"\t" "\t" "lq      $a7,  48($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0,   0($a1)" "\n"
	"\t" "\t" "lq      $t1,  16($a1)" "\n"
	"\t" "\t" "lq      $t2,  32($a1)" "\n"
	"\t" "\t" "lq      $t3,  48($a1)" "\n"
	"\t" "\t" "paddh   $a4, $a4, $t0" "\n"
	"\t" "\t" "paddh   $a5, $a5, $t1" "\n"
	"\t" "\t" "paddh   $a6, $a6, $t2" "\n"
	"\t" "\t" "paddh   $a7, $a7, $t3" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "sq      $a4,   0($a2)" "\n"
	"\t" "\t" "sq      $a6,  32($a2)" "\n"
	"\t" "\t" "lq      $t0, 256($a3)" "\n"
	"\t" "\t" "lq      $t1, 272($a3)" "\n"
	"\t" "\t" "lq      $t2, 288($a3)" "\n"
	"\t" "\t" "lq      $t3, 304($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 64" "\n"
	"\t" "\t" "lq      $a4, 256($a1)" "\n"
	"\t" "\t" "lq      $a5, 272($a1)" "\n"
	"\t" "\t" "lq      $a6, 288($a1)" "\n"
	"\t" "\t" "lq      $a7, 304($a1)" "\n"
	"\t" "\t" "paddh   $t0, $t0, $a4" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "paddh   $t3, $t3, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $t0,  0($at)" "\n"
	"\t" "\t" "sq      $t2, 32($at)" "\n"
	"\t" "\t" "addiu   $at, $at, 64" "\n"
	"\t" "\t" "addiu   $a1, $a1, 64" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "lw      $a2,  4($a0)" "\n"
	"\t" "\t" "lw      $at, 24($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 2" "\n"
	"\t" "\t" "addu    $at, $at, $a2" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "lq      $a4, 256($a3)" "\n"
	"\t" "\t" "lq      $a5, 272($a3)" "\n"
	"\t" "\t" "lq      $a6, 288($a3)" "\n"
	"\t" "\t" "lq      $a7, 304($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0, 256($a1)" "\n"
	"\t" "\t" "lq      $t1, 272($a1)" "\n"
	"\t" "\t" "lq      $t2, 288($a1)" "\n"
	"\t" "\t" "lq      $t3, 304($a1)" "\n"
	"\t" "\t" "paddh   $a4, $a4, $t0" "\n"
	"\t" "\t" "paddh   $a5, $a5, $t1" "\n"
	"\t" "\t" "paddh   $a6, $a6, $t2" "\n"
	"\t" "\t" "paddh   $a7, $a7, $t3" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "ppacb   $a4, $zero, $a4" "\n"
	"\t" "\t" "ppacb   $a5, $zero, $a5" "\n"
	"\t" "\t" "ppacb   $a6, $zero, $a6" "\n"
	"\t" "\t" "ppacb   $a7, $zero, $a7" "\n"
	"\t" "\t" "sd      $a4,  0($a2)" "\n"
	"\t" "\t" "sd      $a5, 16($a2)" "\n"
	"\t" "\t" "sd      $a6, 32($a2)" "\n"
	"\t" "\t" "sd      $a7, 48($a2)" "\n"
	"\t" "\t" "lq      $t0, 320($a3)" "\n"
	"\t" "\t" "lq      $t1, 336($a3)" "\n"
	"\t" "\t" "lq      $t2, 352($a3)" "\n"
	"\t" "\t" "lq      $t3, 368($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 128" "\n"
	"\t" "\t" "lq      $a4, 320($a1)" "\n"
	"\t" "\t" "lq      $a5, 336($a1)" "\n"
	"\t" "\t" "lq      $a6, 352($a1)" "\n"
	"\t" "\t" "lq      $a7, 368($a1)" "\n"
	"\t" "\t" "paddh   $t0, $t0, $a4" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "paddh   $t3, $t3, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $t0, $zero, $t0" "\n"
	"\t" "\t" "ppacb   $t1, $zero, $t1" "\n"
	"\t" "\t" "ppacb   $t2, $zero, $t2" "\n"
	"\t" "\t" "ppacb   $t3, $zero, $t3" "\n"
	"\t" "\t" "sd      $t0,  0($at)" "\n"
	"\t" "\t" "sd      $t1, 16($at)" "\n"
	"\t" "\t" "sd      $t2, 32($at)" "\n"
	"\t" "\t" "sd      $t3, 48($at)" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "addiu   $at, $at, 64" "\n"
	"\t" "\t" "bgtzl   $v1, 2b" "\n"
	"\t" "\t" "addiu   $a1, $a1, 128" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_add_block_ilfl" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_add_block_frfl" "\n"
	"\t" ".ent _MPEG_add_block_frfl" "\n"
	"\t" "_MPEG_add_block_frfl:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "lw      $a2,  0($a0)" "\n"
	"\t" "\t" "lw      $a3, 12($a0)" "\n"
	"\t" "\t" "lw      $a1, 16($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 4" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 8" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $a4,   0($a3)" "\n"
	"\t" "\t" "lq      $a5,  16($a3)" "\n"
	"\t" "\t" "lq      $a6,  32($a3)" "\n"
	"\t" "\t" "lq      $a7,  48($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0,   0($a1)" "\n"
	"\t" "\t" "lq      $t1,  16($a1)" "\n"
	"\t" "\t" "lq      $t2, 256($a1)" "\n"
	"\t" "\t" "lq      $t3, 272($a1)" "\n"
	"\t" "\t" "paddh   $a4, $a4, $t0" "\n"
	"\t" "\t" "paddh   $a5, $a5, $t1" "\n"
	"\t" "\t" "paddh   $a6, $a6, $t2" "\n"
	"\t" "\t" "paddh   $a7, $a7, $t3" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "sq      $a4,   0($a2)" "\n"
	"\t" "\t" "sq      $a6,  16($a2)" "\n"
	"\t" "\t" "lq      $t0,  64($a3)" "\n"
	"\t" "\t" "lq      $t1,  80($a3)" "\n"
	"\t" "\t" "lq      $t2,  96($a3)" "\n"
	"\t" "\t" "lq      $t3, 112($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 128" "\n"
	"\t" "\t" "lq      $a4,  32($a1)" "\n"
	"\t" "\t" "lq      $a5,  48($a1)" "\n"
	"\t" "\t" "lq      $a6, 288($a1)" "\n"
	"\t" "\t" "lq      $a7, 304($a1)" "\n"
	"\t" "\t" "paddh   $t0, $t0, $a4" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "paddh   $t3, $t3, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $t0, 32($a2)" "\n"
	"\t" "\t" "sq      $t2, 48($a2)" "\n"
	"\t" "\t" "addiu   $a1, $a1, 64" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "lw      $a2, 4($a0)" "\n"
	"\t" "\t" "addiu   $v1, $zero, 2" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "lq      $a4,   0($a3)" "\n"
	"\t" "\t" "lq      $a5,  16($a3)" "\n"
	"\t" "\t" "lq      $a6,  32($a3)" "\n"
	"\t" "\t" "lq      $a7,  48($a3)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "lq      $t0, 256($a1)" "\n"
	"\t" "\t" "lq      $t1, 320($a1)" "\n"
	"\t" "\t" "lq      $t2, 272($a1)" "\n"
	"\t" "\t" "lq      $t3, 336($a1)" "\n"
	"\t" "\t" "paddh   $a4, $a4, $t0" "\n"
	"\t" "\t" "paddh   $a5, $a5, $t1" "\n"
	"\t" "\t" "paddh   $a6, $a6, $t2" "\n"
	"\t" "\t" "paddh   $a7, $a7, $t3" "\n"
	"\t" "\t" "pmaxh   $a4, $zero, $a4" "\n"
	"\t" "\t" "pmaxh   $a5, $zero, $a5" "\n"
	"\t" "\t" "pmaxh   $a6, $zero, $a6" "\n"
	"\t" "\t" "pmaxh   $a7, $zero, $a7" "\n"
	"\t" "\t" "pminh   $a4, $v0, $a4" "\n"
	"\t" "\t" "pminh   $a5, $v0, $a5" "\n"
	"\t" "\t" "pminh   $a6, $v0, $a6" "\n"
	"\t" "\t" "pminh   $a7, $v0, $a7" "\n"
	"\t" "\t" "ppacb   $a4, $a5, $a4" "\n"
	"\t" "\t" "ppacb   $a6, $a7, $a6" "\n"
	"\t" "\t" "sq      $a4,  0($a2)" "\n"
	"\t" "\t" "sq      $a6, 16($a2)" "\n"
	"\t" "\t" "lq      $t0,  64($a3)" "\n"
	"\t" "\t" "lq      $t1,  80($a3)" "\n"
	"\t" "\t" "lq      $t2,  96($a3)" "\n"
	"\t" "\t" "lq      $t3, 112($a3)" "\n"
	"\t" "\t" "addiu   $a3, $a3, 128" "\n"
	"\t" "\t" "lq      $a4, 288($a1)" "\n"
	"\t" "\t" "lq      $a5, 352($a1)" "\n"
	"\t" "\t" "lq      $a6, 304($a1)" "\n"
	"\t" "\t" "lq      $a7, 368($a1)" "\n"
	"\t" "\t" "paddh   $t0, $t0, $a4" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "paddh   $t3, $t3, $a7" "\n"
	"\t" "\t" "pmaxh   $t0, $zero, $t0" "\n"
	"\t" "\t" "pmaxh   $t1, $zero, $t1" "\n"
	"\t" "\t" "pmaxh   $t2, $zero, $t2" "\n"
	"\t" "\t" "pmaxh   $t3, $zero, $t3" "\n"
	"\t" "\t" "pminh   $t0, $v0, $t0" "\n"
	"\t" "\t" "pminh   $t1, $v0, $t1" "\n"
	"\t" "\t" "pminh   $t2, $v0, $t2" "\n"
	"\t" "\t" "pminh   $t3, $v0, $t3" "\n"
	"\t" "\t" "ppacb   $t0, $t1, $t0" "\n"
	"\t" "\t" "ppacb   $t2, $t3, $t2" "\n"
	"\t" "\t" "sq      $t0, 32($a2)" "\n"
	"\t" "\t" "sq      $t2, 48($a2)" "\n"
	"\t" "\t" "addiu   $a2, $a2, 64" "\n"
	"\t" "\t" "bgtzl   $v1, 2b" "\n"
	"\t" "\t" "addiu   $a1, $a1, 128" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_add_block_frfl" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_luma" "\n"
	"\t" ".ent _MPEG_put_luma" "\n"
	"\t" "_MPEG_put_luma:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t1, $t2, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t1" "\n"
	"\t" "\t" "pextub  $t1, $zero, $t1" "\n"
	"\t" "\t" "sq      $t2,  0($a2)" "\n"
	"\t" "\t" "sq      $t1, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_luma" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_chroma" "\n"
	"\t" ".ent _MPEG_put_chroma" "\n"
	"\t" "_MPEG_put_chroma:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t2,  64($a1)" "\n"
	"\t" "\t" "ld      $t3, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "pcpyld  $t1, $t3, $t1" "\n"
	"\t" "\t" "pcpyld  $t2, $t8, $t2" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t2, $t2, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "sq      $t1,   0($a2)" "\n"
	"\t" "\t" "sq      $t2, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_chroma" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_luma_X" "\n"
	"\t" ".ent _MPEG_put_luma_X" "\n"
	"\t" "_MPEG_put_luma_X:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "qfsrv   $t3, $t2, $t1" "\n"
	"\t" "\t" "qfsrv   $t8, $t1, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t3" "\n"
	"\t" "\t" "pextub  $t2, $zero, $t3" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t8, $t8, $t3" "\n"
	"\t" "\t" "pextlb  $t3, $zero, $t8" "\n"
	"\t" "\t" "pextub  $t8, $zero, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t3" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $v0" "\n"
	"\t" "\t" "paddh   $t2, $t2, $v0" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "sq      $t1,  0($a2)" "\n"
	"\t" "\t" "sq      $t2, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_luma_X" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_chroma_X" "\n"
	"\t" ".ent _MPEG_put_chroma_X" "\n"
	"\t" "_MPEG_put_chroma_X:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t2,  64($a1)" "\n"
	"\t" "\t" "ld      $t3, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "pcpyld  $t1, $t3, $t1" "\n"
	"\t" "\t" "pcpyld  $t2, $t8, $t2" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t2, $t2, $t2" "\n"
	"\t" "\t" "addiu   $t9, $zero, 1" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "mtsab   $t9, 0" "\n"
	"\t" "\t" "qfsrv   $a5, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $a6, $t2, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "pextlb  $a5, $zero, $a5" "\n"
	"\t" "\t" "pextlb  $a6, $zero, $a6" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "paddh   $t1, $t1, $v0" "\n"
	"\t" "\t" "paddh   $t2, $t2, $v0" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "sq      $t1,   0($a2)" "\n"
	"\t" "\t" "sq      $t2, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_chroma_X" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_luma_Y" "\n"
	"\t" ".ent _MPEG_put_luma_Y" "\n"
	"\t" "_MPEG_put_luma_Y:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "lq      $t3,   0($a1)" "\n"
	"\t" "\t" "lq      $t8, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t3, $t8, $t3" "\n"
	"\t" "\t" "pextub  $t8, $zero, $t3" "\n"
	"\t" "\t" "pextlb  $t3, $zero, $t3" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t1, $t2, $t1" "\n"
	"\t" "\t" "pextub  $t2, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "paddh   $v0, $t2, $t8" "\n"
	"\t" "\t" "pnor    $t8, $zero, $zero" "\n"
	"\t" "\t" "paddh   $t9, $t1, $t3" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 15" "\n"
	"\t" "\t" "por     $t3, $zero, $t1" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t8" "\n"
	"\t" "\t" "paddh   $v0, $v0, $t8" "\n"
	"\t" "\t" "por     $t8, $zero, $t2" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 1" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 1" "\n"
	"\t" "\t" "sq      $t9,  0($a2)" "\n"
	"\t" "\t" "sq      $v0, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_luma_Y" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_chroma_Y" "\n"
	"\t" ".ent _MPEG_put_chroma_Y" "\n"
	"\t" "_MPEG_put_chroma_Y:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "ld      $a0,   0($a1)" "\n"
	"\t" "\t" "ld      $a3,  64($a1)" "\n"
	"\t" "\t" "ld      $a4, 384($a1)" "\n"
	"\t" "\t" "ld      $a5, 448($a1)" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "\t" "pcpyld  $a0, $a4, $a0" "\n"
	"\t" "\t" "pcpyld  $a3, $a5, $a3" "\n"
	"\t" "\t" "qfsrv   $a0, $a0, $a0" "\n"
	"\t" "\t" "qfsrv   $a3, $a3, $a3" "\n"
	"\t" "\t" "pextlb  $a0, $zero, $a0" "\n"
	"\t" "\t" "pextlb  $a3, $zero, $a3" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t2,  64($a1)" "\n"
	"\t" "\t" "ld      $t3, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "pcpyld  $t1, $t3, $t1" "\n"
	"\t" "\t" "pcpyld  $t2, $t8, $t2" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t2, $t2, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "paddh   $a5, $t1, $a0" "\n"
	"\t" "\t" "paddh   $a6, $t2, $a3" "\n"
	"\t" "\t" "por     $a0, $zero, $t1" "\n"
	"\t" "\t" "por     $a3, $zero, $t2" "\n"
	"\t" "\t" "paddh   $a5, $a5, $v0" "\n"
	"\t" "\t" "paddh   $a6, $a6, $v0" "\n"
	"\t" "\t" "psrlh   $a5, $a5, 1" "\n"
	"\t" "\t" "psrlh   $a6, $a6, 1" "\n"
	"\t" "\t" "sq      $a5,   0($a2)" "\n"
	"\t" "\t" "sq      $a6, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_chroma_Y" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_luma_XY" "\n"
	"\t" ".ent _MPEG_put_luma_XY" "\n"
	"\t" "_MPEG_put_luma_XY:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "lq      $v0,   0($a1)" "\n"
	"\t" "\t" "lq      $t3, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "qfsrv   $t8, $t3, $v0" "\n"
	"\t" "\t" "qfsrv   $t9, $v0, $t3" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "pextlb  $v0, $zero, $t8" "\n"
	"\t" "\t" "pextub  $t3, $zero, $t8" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "qfsrv   $t9, $t9, $t8" "\n"
	"\t" "\t" "pextlb  $t8, $zero, $t9" "\n"
	"\t" "\t" "pextub  $t9, $zero, $t9" "\n"
	"\t" "\t" "paddh   $v0, $v0, $t8" "\n"
	"\t" "\t" "paddh   $t3, $t3, $t9" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "qfsrv   $t8, $t2, $t1" "\n"
	"\t" "\t" "qfsrv   $t9, $t1, $t2" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t8" "\n"
	"\t" "\t" "pextub  $t2, $zero, $t8" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "qfsrv   $t9, $t9, $t8" "\n"
	"\t" "\t" "pextlb  $t8, $zero, $t9" "\n"
	"\t" "\t" "pextub  $t9, $zero, $t9" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t8" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t9" "\n"
	"\t" "\t" "paddh   $t8, $v0, $t1" "\n"
	"\t" "\t" "paddh   $t9, $t3, $t2" "\n"
	"\t" "\t" "por     $v0, $zero, $t1" "\n"
	"\t" "\t" "pnor    $t1, $zero, $zero" "\n"
	"\t" "\t" "por     $t3, $zero, $t2" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psllh   $t1, $t1,  1" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t1" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t1" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 2" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 2" "\n"
	"\t" "\t" "sq      $t8,  0($a2)" "\n"
	"\t" "\t" "sq      $t9, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_luma_XY" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_put_chroma_XY" "\n"
	"\t" ".ent _MPEG_put_chroma_XY" "\n"
	"\t" "_MPEG_put_chroma_XY:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "pnor    $t9, $zero, $zero" "\n"
	"\t" "\t" "ld      $a0,   0($a1)" "\n"
	"\t" "\t" "ld      $v0,  64($a1)" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "ld      $a4, 384($a1)" "\n"
	"\t" "\t" "ld      $a5, 448($a1)" "\n"
	"\t" "\t" "pcpyld  $a0, $a4, $a0" "\n"
	"\t" "\t" "pcpyld  $v0, $a5, $v0" "\n"
	"\t" "\t" "qfsrv   $a0, $a0, $a0" "\n"
	"\t" "\t" "qfsrv   $v0, $v0, $v0" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 15" "\n"
	"\t" "\t" "psllh   $t9, $t9, 1" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $a4, $a0, $a0" "\n"
	"\t" "\t" "qfsrv   $a5, $v0, $v0" "\n"
	"\t" "\t" "pextlb  $a0, $zero, $a0" "\n"
	"\t" "\t" "pextlb  $v0, $zero, $v0" "\n"
	"\t" "\t" "pextlb  $a4, $zero, $a4" "\n"
	"\t" "\t" "pextlb  $a5, $zero, $a5" "\n"
	"\t" "\t" "paddh   $a0, $a0, $a4" "\n"
	"\t" "\t" "paddh   $a4, $v0, $a5" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t3,  64($a1)" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "ld      $t2, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "pcpyld  $t1, $t2, $t1" "\n"
	"\t" "\t" "pcpyld  $t3, $t8, $t3" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t3, $t3, $t3" "\n"
	"\t" "\t" "addiu   $v0, $zero, 1" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "mtsab   $v0, 0" "\n"
	"\t" "\t" "qfsrv   $t2, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t8, $t3, $t3" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t3, $zero, $t3" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "pextlb  $t8, $zero, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $t2, $t3, $t8" "\n"
	"\t" "\t" "paddh   $t3, $a0, $t1" "\n"
	"\t" "\t" "paddh   $t8, $a4, $t2" "\n"
	"\t" "\t" "por     $a0, $zero, $t1" "\n"
	"\t" "\t" "por     $a4, $zero, $t2" "\n"
	"\t" "\t" "paddh   $t3, $t3, $t9" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t9" "\n"
	"\t" "\t" "psrlh   $t3, $t3, 2" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 2" "\n"
	"\t" "\t" "sq      $t3,   0($a2)" "\n"
	"\t" "\t" "sq      $t8, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_put_chroma_XY" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_luma" "\n"
	"\t" ".ent _MPEG_avg_luma" "\n"
	"\t" "_MPEG_avg_luma:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t1, $t2, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t1" "\n"
	"\t" "\t" "pextub  $t1, $zero, $t1" "\n"
	"\t" "\t" "lq      $t8,  0($a2)" "\n"
	"\t" "\t" "lq      $t9, 16($a2)" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t9" "\n"
	"\t" "\t" "pcgth   $t8, $t2, $zero" "\n"
	"\t" "\t" "pcgth   $t9, $t1, $zero" "\n"
	"\t" "\t" "pceqh   $v0, $t2, $zero" "\n"
	"\t" "\t" "pceqh   $t3, $t1, $zero" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 15" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 15" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "\t" "psrlh   $t3, $t3, 15" "\n"
	"\t" "\t" "por     $t8, $t8, $v0" "\n"
	"\t" "\t" "por     $t9, $t9, $t3" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t9" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "sq      $t2,  0($a2)" "\n"
	"\t" "\t" "sq      $t1, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_luma" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_chroma" "\n"
	"\t" ".ent _MPEG_avg_chroma" "\n"
	"\t" "_MPEG_avg_chroma:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t2,  64($a1)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "ld      $t3, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "pcpyld  $t1, $t3, $t1" "\n"
	"\t" "\t" "pcpyld  $t2, $t8, $t2" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t2, $t2, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "lq      $a4,   0($a2)" "\n"
	"\t" "\t" "lq      $a5, 128($a2)" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a4" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a5" "\n"
	"\t" "\t" "pcgth   $a4, $t1, $zero" "\n"
	"\t" "\t" "pcgth   $a5, $t2, $zero" "\n"
	"\t" "\t" "pceqh   $v0, $t1, $zero" "\n"
	"\t" "\t" "pceqh   $t9, $t2, $zero" "\n"
	"\t" "\t" "psrlh   $a4, $a4, 15" "\n"
	"\t" "\t" "psrlh   $a5, $a5, 15" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 15" "\n"
	"\t" "\t" "por     $a4, $a4, $v0" "\n"
	"\t" "\t" "por     $a5, $a5, $t9" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a4" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a5" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "sq      $t1,   0($a2)" "\n"
	"\t" "\t" "sq      $t2, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_chroma" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_luma_X" "\n"
	"\t" ".ent _MPEG_avg_luma_X" "\n"
	"\t" "_MPEG_avg_luma_X:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "qfsrv   $t3, $t2, $t1" "\n"
	"\t" "\t" "qfsrv   $t8, $t1, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t3" "\n"
	"\t" "\t" "pextub  $t2, $zero, $t3" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t8, $t8, $t3" "\n"
	"\t" "\t" "pextlb  $t3, $zero, $t8" "\n"
	"\t" "\t" "pextub  $t8, $zero, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t3" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $v0" "\n"
	"\t" "\t" "paddh   $t2, $t2, $v0" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "lq      $t8,  0($a2)" "\n"
	"\t" "\t" "lq      $t9, 16($a2)" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t8" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t9" "\n"
	"\t" "\t" "pcgth   $t8, $t1, $zero" "\n"
	"\t" "\t" "pceqh   $t9, $t1, $zero" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 15" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 15" "\n"
	"\t" "\t" "por     $t8, $t8, $t9" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t8" "\n"
	"\t" "\t" "pcgth   $t8, $t2, $zero" "\n"
	"\t" "\t" "pceqh   $t9, $t2, $zero" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 15" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 15" "\n"
	"\t" "\t" "por     $t8, $t8, $t9" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t8" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "sq      $t1,  0($a2)" "\n"
	"\t" "\t" "sq      $t2, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_luma_X" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_chroma_X" "\n"
	"\t" ".ent _MPEG_avg_chroma_X" "\n"
	"\t" "_MPEG_avg_chroma_X:" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t2,  64($a1)" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "ld      $t3, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "pcpyld  $t1, $t3, $t1" "\n"
	"\t" "\t" "pcpyld  $t2, $t8, $t2" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t2, $t2, $t2" "\n"
	"\t" "\t" "addiu   $t9, $zero, 1" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "mtsab   $t9, 0" "\n"
	"\t" "\t" "qfsrv   $a5, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $a6, $t2, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "pextlb  $a5, $zero, $a5" "\n"
	"\t" "\t" "pextlb  $a6, $zero, $a6" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "paddh   $t1, $t1, $v0" "\n"
	"\t" "\t" "paddh   $t2, $t2, $v0" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "lq      $a5,   0($a2)" "\n"
	"\t" "\t" "lq      $a6, 128($a2)" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "pcgth   $a5, $t1, $zero" "\n"
	"\t" "\t" "pcgth   $a6, $t2, $zero" "\n"
	"\t" "\t" "pceqh   $t9, $t1, $zero" "\n"
	"\t" "\t" "pceqh   $a0, $t2, $zero" "\n"
	"\t" "\t" "psrlh   $a5, $a5, 15" "\n"
	"\t" "\t" "psrlh   $a6, $a6, 15" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 15" "\n"
	"\t" "\t" "psrlh   $a0, $a0, 15" "\n"
	"\t" "\t" "por     $a5, $a5, $t9" "\n"
	"\t" "\t" "por     $a6, $a6, $a0" "\n"
	"\t" "\t" "paddh   $t1, $t1, $a5" "\n"
	"\t" "\t" "paddh   $t2, $t2, $a6" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 1" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 1" "\n"
	"\t" "\t" "sq      $t1,   0($a2)" "\n"
	"\t" "\t" "sq      $t2, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_chroma_X" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_luma_Y" "\n"
	"\t" ".ent _MPEG_avg_luma_Y" "\n"
	"\t" "_MPEG_avg_luma_Y:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "lq      $t3,   0($a1)" "\n"
	"\t" "\t" "lq      $t8, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t3, $t8, $t3" "\n"
	"\t" "\t" "pextub  $t8, $zero, $t3" "\n"
	"\t" "\t" "pextlb  $t3, $zero, $t3" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $t1, $t2, $t1" "\n"
	"\t" "\t" "pextub  $t2, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "paddh   $v0, $t2, $t8" "\n"
	"\t" "\t" "pnor    $t8, $zero, $zero" "\n"
	"\t" "\t" "paddh   $t9, $t1, $t3" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 15" "\n"
	"\t" "\t" "por     $t3, $zero, $t1" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t8" "\n"
	"\t" "\t" "paddh   $v0, $v0, $t8" "\n"
	"\t" "\t" "por     $t8, $zero, $t2" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 1" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 1" "\n"
	"\t" "\t" "lq      $t1,  0($a2)" "\n"
	"\t" "\t" "lq      $t2, 16($a2)" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t1" "\n"
	"\t" "\t" "paddh   $v0, $v0, $t2" "\n"
	"\t" "\t" "pcgth   $t1, $t9, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $t9, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t1" "\n"
	"\t" "\t" "pcgth   $t1, $v0, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $v0, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $v0, $v0, $t1" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 1" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 1" "\n"
	"\t" "\t" "sq      $t9,  0($a2)" "\n"
	"\t" "\t" "sq      $v0, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_luma_Y" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_chroma_Y" "\n"
	"\t" ".ent _MPEG_avg_chroma_Y" "\n"
	"\t" "_MPEG_avg_chroma_Y:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "ld      $a0,   0($a1)" "\n"
	"\t" "\t" "ld      $a3,  64($a1)" "\n"
	"\t" "\t" "ld      $a4, 384($a1)" "\n"
	"\t" "\t" "ld      $a5, 448($a1)" "\n"
	"\t" "\t" "pnor    $v0, $zero, $zero" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "psrlh   $v0, $v0, 15" "\n"
	"\t" "\t" "pcpyld  $a0, $a4, $a0" "\n"
	"\t" "\t" "pcpyld  $a3, $a5, $a3" "\n"
	"\t" "\t" "qfsrv   $a0, $a0, $a0" "\n"
	"\t" "\t" "qfsrv   $a3, $a3, $a3" "\n"
	"\t" "\t" "pextlb  $a0, $zero, $a0" "\n"
	"\t" "\t" "pextlb  $a3, $zero, $a3" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t2,  64($a1)" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "ld      $t3, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "pcpyld  $t1, $t3, $t1" "\n"
	"\t" "\t" "pcpyld  $t2, $t8, $t2" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t2, $t2, $t2" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "paddh   $a5, $t1, $a0" "\n"
	"\t" "\t" "paddh   $a6, $t2, $a3" "\n"
	"\t" "\t" "por     $a0, $zero, $t1" "\n"
	"\t" "\t" "por     $a3, $zero, $t2" "\n"
	"\t" "\t" "paddh   $a5, $a5, $v0" "\n"
	"\t" "\t" "paddh   $a6, $a6, $v0" "\n"
	"\t" "\t" "psrlh   $a5, $a5, 1" "\n"
	"\t" "\t" "psrlh   $a6, $a6, 1" "\n"
	"\t" "\t" "lq      $t1,   0($a2)" "\n"
	"\t" "\t" "lq      $t2, 128($a2)" "\n"
	"\t" "\t" "paddh   $a5, $a5, $t1" "\n"
	"\t" "\t" "paddh   $a6, $a6, $t2" "\n"
	"\t" "\t" "pcgth   $t1, $a5, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $a5, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $a5, $a5, $t1" "\n"
	"\t" "\t" "pcgth   $t1, $a6, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $a6, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $a6, $a6, $t1" "\n"
	"\t" "\t" "psrlh   $a5, $a5, 1" "\n"
	"\t" "\t" "psrlh   $a6, $a6, 1" "\n"
	"\t" "\t" "sq      $a5,   0($a2)" "\n"
	"\t" "\t" "sq      $a6, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_chroma_Y" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_luma_XY" "\n"
	"\t" ".ent _MPEG_avg_luma_XY" "\n"
	"\t" "_MPEG_avg_luma_XY:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "lq      $v0,   0($a1)" "\n"
	"\t" "\t" "lq      $t3, 384($a1)" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "qfsrv   $t8, $t3, $v0" "\n"
	"\t" "\t" "qfsrv   $t9, $v0, $t3" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "pextlb  $v0, $zero, $t8" "\n"
	"\t" "\t" "pextub  $t3, $zero, $t8" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "qfsrv   $t9, $t9, $t8" "\n"
	"\t" "\t" "pextlb  $t8, $zero, $t9" "\n"
	"\t" "\t" "pextub  $t9, $zero, $t9" "\n"
	"\t" "\t" "paddh   $v0, $v0, $t8" "\n"
	"\t" "\t" "paddh   $t3, $t3, $t9" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "lq      $t1,   0($a1)" "\n"
	"\t" "\t" "lq      $t2, 384($a1)" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "qfsrv   $t8, $t2, $t1" "\n"
	"\t" "\t" "qfsrv   $t9, $t1, $t2" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t8" "\n"
	"\t" "\t" "pextub  $t2, $zero, $t8" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "qfsrv   $t9, $t9, $t8" "\n"
	"\t" "\t" "pextlb  $t8, $zero, $t9" "\n"
	"\t" "\t" "pextub  $t9, $zero, $t9" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t8" "\n"
	"\t" "\t" "paddh   $t2, $t2, $t9" "\n"
	"\t" "\t" "paddh   $t8, $v0, $t1" "\n"
	"\t" "\t" "paddh   $t9, $t3, $t2" "\n"
	"\t" "\t" "por     $v0, $zero, $t1" "\n"
	"\t" "\t" "pnor    $t1, $zero, $zero" "\n"
	"\t" "\t" "por     $t3, $zero, $t2" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psllh   $t1, $t1,  1" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t1" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t1" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 2" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 2" "\n"
	"\t" "\t" "lq      $t1,  0($a2)" "\n"
	"\t" "\t" "lq      $t2, 16($a2)" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t1" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t2" "\n"
	"\t" "\t" "pcgth   $t1, $t8, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $t8, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t1" "\n"
	"\t" "\t" "pcgth   $t1, $t9, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $t9, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $t9, $t9, $t1" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 1" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 1" "\n"
	"\t" "\t" "sq      $t8,  0($a2)" "\n"
	"\t" "\t" "sq      $t9, 16($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 32" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 512" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_luma_XY" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_avg_chroma_XY" "\n"
	"\t" ".ent _MPEG_avg_chroma_XY" "\n"
	"\t" "_MPEG_avg_chroma_XY:" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "pnor    $t9, $zero, $zero" "\n"
	"\t" "\t" "ld      $a0,   0($a1)" "\n"
	"\t" "\t" "ld      $v0,  64($a1)" "\n"
	"\t" "\t" "mtsab   $zero, 1" "\n"
	"\t" "\t" "ld      $a4, 384($a1)" "\n"
	"\t" "\t" "ld      $a5, 448($a1)" "\n"
	"\t" "\t" "pcpyld  $a0, $a4, $a0" "\n"
	"\t" "\t" "pcpyld  $v0, $a5, $v0" "\n"
	"\t" "\t" "qfsrv   $a0, $a0, $a0" "\n"
	"\t" "\t" "qfsrv   $v0, $v0, $v0" "\n"
	"\t" "\t" "psrlh   $t9, $t9, 15" "\n"
	"\t" "\t" "psllh   $t9, $t9,  1" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "qfsrv   $a4, $a0, $a0" "\n"
	"\t" "\t" "qfsrv   $a5, $v0, $v0" "\n"
	"\t" "\t" "pextlb  $a0, $zero, $a0" "\n"
	"\t" "\t" "pextlb  $v0, $zero, $v0" "\n"
	"\t" "\t" "pextlb  $a4, $zero, $a4" "\n"
	"\t" "\t" "pextlb  $a5, $zero, $a5" "\n"
	"\t" "\t" "paddh   $a0, $a0, $a4" "\n"
	"\t" "\t" "paddh   $a4, $v0, $a5" "\n"
	"\t" "\t" "beq     $v1, $zero, 2f" "\n"
	"\t" "\t" "addiu   $at, $at, 1" "\n"
	"\t" "1:" "\n"
	"\t" "\t" "ld      $t1,   0($a1)" "\n"
	"\t" "\t" "ld      $t3,  64($a1)" "\n"
	"\t" "\t" "mtsab   $a3, 0" "\n"
	"\t" "\t" "ld      $t2, 384($a1)" "\n"
	"\t" "\t" "ld      $t8, 448($a1)" "\n"
	"\t" "\t" "pcpyld  $t1, $t2, $t1" "\n"
	"\t" "\t" "pcpyld  $t3, $t8, $t3" "\n"
	"\t" "\t" "qfsrv   $t1, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t3, $t3, $t3" "\n"
	"\t" "\t" "addiu   $v0, $zero, 1" "\n"
	"\t" "\t" "addu    $a1, $a1, $a7" "\n"
	"\t" "\t" "addiu   $v1, $v1, -1" "\n"
	"\t" "\t" "mtsab   $v0, 0" "\n"
	"\t" "\t" "qfsrv   $t2, $t1, $t1" "\n"
	"\t" "\t" "qfsrv   $t8, $t3, $t3" "\n"
	"\t" "\t" "pextlb  $t1, $zero, $t1" "\n"
	"\t" "\t" "pextlb  $t3, $zero, $t3" "\n"
	"\t" "\t" "pextlb  $t2, $zero, $t2" "\n"
	"\t" "\t" "pextlb  $t8, $zero, $t8" "\n"
	"\t" "\t" "paddh   $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $t2, $t3, $t8" "\n"
	"\t" "\t" "paddh   $t3, $a0, $t1" "\n"
	"\t" "\t" "paddh   $t8, $a4, $t2" "\n"
	"\t" "\t" "por     $a0, $zero, $t1" "\n"
	"\t" "\t" "por     $a4, $zero, $t2" "\n"
	"\t" "\t" "paddh   $t3, $t3, $t9" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t9" "\n"
	"\t" "\t" "psrlh   $t3, $t3, 2" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 2" "\n"
	"\t" "\t" "lq      $t1,   0($a2)" "\n"
	"\t" "\t" "lq      $t2, 128($a2)" "\n"
	"\t" "\t" "paddh   $t3, $t3, $t1" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t2" "\n"
	"\t" "\t" "pcgth   $t1, $t3, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $t3, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $t3, $t3, $t1" "\n"
	"\t" "\t" "pcgth   $t1, $t8, $zero" "\n"
	"\t" "\t" "pceqh   $t2, $t8, $zero" "\n"
	"\t" "\t" "psrlh   $t1, $t1, 15" "\n"
	"\t" "\t" "psrlh   $t2, $t2, 15" "\n"
	"\t" "\t" "por     $t1, $t1, $t2" "\n"
	"\t" "\t" "paddh   $t8, $t8, $t1" "\n"
	"\t" "\t" "psrlh   $t3, $t3, 1" "\n"
	"\t" "\t" "psrlh   $t8, $t8, 1" "\n"
	"\t" "\t" "sq      $t3,   0($a2)" "\n"
	"\t" "\t" "sq      $t8, 128($a2)" "\n"
	"\t" "\t" "bgtz    $v1, 1b" "\n"
	"\t" "\t" "addiu   $a2, $a2, 16" "\n"
	"\t" "2:" "\n"
	"\t" "\t" "addu    $v1, $zero, $at" "\n"
	"\t" "\t" "addiu   $a1, $a1, 704" "\n"
	"\t" "\t" "bgtzl   $v1, 1b" "\n"
	"\t" "\t" "addu    $at, $zero, $zero" "\n"
	"\t" "\t" "jr      $ra" "\n"
	"\t" "\t" "nop" "\n"
	"\t" ".end _MPEG_avg_chroma_XY" "\n"

	"\t" ".set pop" "\n"
);

__asm__
(
	"\t" ".set push" "\n"
	"\t" ".set noreorder" "\n"
	"\t" ".set nomacro" "\n"
	"\t" ".set noat" "\n"

	"\t" ".globl _MPEG_do_mc" "\n"
	"\t" ".ent _MPEG_do_mc" "\n"
	"\t" "_MPEG_do_mc:" "\n"
	"\t" "\t" "addiu   $v0, $zero, 16" "\n"
	"\t" "\t" "lw      $a1,  0($a0)" "\n"
	"\t" "\t" "addiu   $sp, $sp, -16" "\n"
	"\t" "\t" "lw      $a2,  4($a0)" "\n"
	"\t" "\t" "lw      $a3, 12($a0)" "\n"
	"\t" "\t" "lw      $a4, 16($a0)" "\n"
	"\t" "\t" "lw      $a5, 20($a0)" "\n"
	"\t" "\t" "lw      $a6, 24($a0)" "\n"
	"\t" "\t" "lw      $t0, 28($a0)" "\n"
	"\t" "\t" "subu    $a4, $a4, $t0" "\n"
	"\t" "\t" "lw      $t1, 32($a0)" "\n"
	"\t" "\t" "sll     $t0, $t0, 4" "\n"
	"\t" "\t" "addu    $a1, $a1, $t0" "\n"
	"\t" "\t" "subu    $v1, $v0, $a4" "\n"
	"\t" "\t" "sllv    $a7, $v0, $a6" "\n"
	"\t" "\t" "srlv    $v1, $v1, $a6" "\n"
	"\t" "\t" "sll     $at, $a4, 4" "\n"
	"\t" "\t" "sw      $ra, 0($sp)" "\n"
	"\t" "\t" "addu    $a1, $a1, $at" "\n"
	"\t" "\t" "jalr    $t1" "\n"
	"\t" "\t" "subu    $at, $a5, $v1" "\n"
	"\t" "\t" "lw      $a1,  0($a0)" "\n"
	"\t" "\t" "lw      $a2,  8($a0)" "\n"
	"\t" "\t" "lw      $t1, 36($a0)" "\n"
	"\t" "\t" "addiu   $a1, $a1, 256" "\n"
	"\t" "\t" "srl     $t0, $t0, 1" "\n"
	"\t" "\t" "srl     $a3, $a3, 1" "\n"
	"\t" "\t" "srl     $a4, $a4, 1" "\n"
	"\t" "\t" "srl     $a5, $a5, 1" "\n"
	"\t" "\t" "lw      $ra, 0($sp)" "\n"
	"\t" "\t" "srlv    $a4, $a4, $a6" "\n"
	"\t" "\t" "addu    $a1, $a1, $t0" "\n"
	"\t" "\t" "addiu   $v0, $zero, 8" "\n"
	"\t" "\t" "sllv    $a4, $a4, $a6" "\n"
	"\t" "\t" "subu    $v1, $v0, $a4" "\n"
	"\t" "\t" "sllv    $a7, $v0, $a6" "\n"
	"\t" "\t" "srlv    $v1, $v1, $a6" "\n"
	"\t" "\t" "sll     $at, $a4, 3" "\n"
	"\t" "\t" "addu    $a1, $a1, $at" "\n"
	"\t" "\t" "subu    $at, $a5, $v1" "\n"
	"\t" "\t" "jr      $t1" "\n"
	"\t" "\t" "addiu   $sp, $sp, 16" "\n"
	"\t" ".end _MPEG_do_mc" "\n"

	"\t" ".set pop" "\n"
);
