# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_BIN_ALTNAMES ?=

IOP_BIN ?= intrmanp.irx

IOP_SRC_DIR = $(PS2SDKSRC)/iop/system/intrman/src/
IOP_INC_DIR = $(PS2SDKSRC)/iop/system/intrman/include/

INTRMAN_PS1 ?= 1

include $(PS2SDKSRC)/iop/system/intrman/Makefile
