# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

SUBDIRS = erl kernel libcglue libpthreadglue rpc startup debug \
	eedebug sbv dma graph math3d \
	packet packet2 draw libgs \
	libvux font input inputx network iopreboot \
	mpeg \
	elf-loader

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make
include $(PS2SDKSRC)/ee/Rules.release
