int fs_init(iop_device_t *driver);
int fs_deinit(iop_device_t *driver);
int fs_open(iop_file_t* fd, const char *name, int mode);
int fs_close(iop_file_t* fd);
int fs_lseek(iop_file_t* fd, unsigned long offset, int whence);
int fs_write(iop_file_t* fd, void * buffer, int size );
int fs_read(iop_file_t* fd, void * buffer, int size );
int fs_remove(iop_file_t *fd, const char *name);
int fs_mkdir(iop_file_t *fd, const char *name);
int fs_rmdir(iop_file_t *fd, const char *name);
int fs_dopen(iop_file_t *fd, const char *name);
int fs_dclose(iop_file_t *fd);
int fs_dread(iop_file_t *fd, fio_dirent_t *buffer);
int fs_getstat(iop_file_t *fd, const char *name, fio_stat_t *stat);
int fs_ioctl(iop_file_t *fd, unsigned long request, void *data);
