# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_BIN_ALTNAMES =

IOP_SRC_DIR = $(PS2SDKSRC)/iop/system/sysclib/src/
IOP_INC_DIR = $(PS2SDKSRC)/iop/system/sysclib/include/

USE_MIPS_ASM ?= 0
USE_SIZE_OPTIMIZED ?= 1
USE_FULL_PRINTF ?= 0

include $(PS2SDKSRC)/iop/system/sysclib/Makefile
