# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

SUBDIRS  = ahx
SUBDIRS += audsrv
SUBDIRS += camera
SUBDIRS += cdvd
SUBDIRS += filexio
SUBDIRS += hdd
SUBDIRS += keyboard
SUBDIRS += memorycard
SUBDIRS += mouse
SUBDIRS += multitap
SUBDIRS += pad
SUBDIRS += poweroff
SUBDIRS += ps2snd
SUBDIRS += remote
SUBDIRS += secr
SUBDIRS += sior
SUBDIRS += tcpips
SUBDIRS += xcdvd

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make
