# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_BIN_ALTNAMES =

IOP_SRC_DIR = $(PS2SDKSRC)/iop/system/sio2man/src/
IOP_INC_DIR = $(PS2SDKSRC)/iop/system/sio2man/include/

IOP_CFLAGS += -DSIO2LOG

include $(PS2SDKSRC)/iop/system/sio2man/Makefile
