# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2025, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_BIN_ALTNAMES = 

PARENT_DIR=$(PS2SDKSRC)/iop/memorycard/mcman

IOP_SRC_DIR = $(PARENT_DIR)/src/
IOP_INC_DIR = $(PARENT_DIR)/include/

IOP_BIN = dongleman.irx

MCMAN_BUILDING_DONGLEMAN ?= 1

include $(PARENT_DIR)/Makefile
