# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_SRC_DIR = $(PS2SDKSRC)/iop/hdd/pfs/src/

IOP_BIN ?= ps2fs-osd.irx

IOP_CFLAGS += -DPFS_OSD_VER

include $(PS2SDKSRC)/iop/hdd/pfs/Makefile
