
__asm__
(
	"\t" ".global  WriteBackDCache" "\n"
	"\t" ".ent     WriteBackDCache" "\n"
	"\t" "WriteBackDCache:" "\n"

	"\t" "\t" "lui    $25, 0xffff" "\n"
	"\t" "\t" "ori    $25, $25, 0xffc0" "\n"
	"\t" "\t" "blez   $5, last" "\n"
	"\t" "\t" "addu   $10, $4, $5" "\n"
	"\t" "\t" "and    $8, $4, $25" "\n"
	"\t" "\t" "addiu  $10, $10, -1" "\n"
	"\t" "\t" "and    $9, $10, $25" "\n"
	"\t" "\t" "subu   $10, $9, $8" "\n"
	"\t" "\t" "srl    $11, $10, 0x6" "\n"
	"\t" "\t" "addiu  $11, $11, 1" "\n"
	"\t" "\t" "andi   $9, $11, 0x7" "\n"
	"\t" "\t" "beqz   $9, eight" "\n"
	"\t" "\t" "srl    $10, $11, 0x3" "\n"
	"\t" "loop1:" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 0($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "addiu    $9, $9, -1" "\n"
	"\t" "\t" "nop" "\n"
	"\t" "\t" "bgtz     $9, loop1" "\n"
	"\t" "\t" "addiu    $8, $8, 64" "\n"

	"\t" "eight:" "\n"
	"\t" "\t" "beqz     $10, last" "\n"
	"\t" "loop8:" "\n"
	"\t" "\t" "addiu    $10, $10, -1" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 0($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 64($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 128($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 192($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 256($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 320($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 384($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "cache    0x18, 448($8)" "\n"
	"\t" "\t" "sync" "\n"
	"\t" "\t" "bgtz     $10, loop8" "\n"
	"\t" "\t" "addiu    $8, $8, 512" "\n"
	"\t" "last:" "\n"
	"\t" "\t" "jr       $31" "\n"
	"\t" "\t" "nop" "\n"

	"\t" ".end    WriteBackDCache" "\n"
);
