function(compile_multiple target objects srcfile)
    foreach(obj ${objects})
        add_library(${obj} OBJECT ${srcfile})
        get_filename_component(def ${obj} NAME_WLE)
        target_compile_definitions(${obj} PUBLIC "F_${def}")
        target_include_directories(${obj} PRIVATE include)
        target_link_libraries(${target} private ${obj})
    endforeach()
endfunction()
