# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

EE_SRC_DIR = $(PS2SDKSRC)/ee/rpc/pad/src/
EE_INC_DIR = $(PS2SDKSRC)/ee/rpc/pad/include/

EE_CFLAGS += -D_XPAD

include $(PS2SDKSRC)/ee/rpc/pad/Makefile
