# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_IMPORT_INCS += \
	system/intrman \
	system/loadcore \
	system/stdio \
	system/sysclib \
	system/sysmem

IOP_OBJS = \
	config.o \
	s_cb.o \
	s_crwa.o \
	s_dcb.o \
	s_do.o \
	s_f.o \
	s_gav.o \
	s_gca.o \
	s_gccm.o \
	s_gccr.o \
	s_gccv.o \
	s_gcmv.o \
	s_gcmva.o \
	s_gcmvx.o \
	s_gi.o \
	s_gia.o \
	s_gks.o \
	s_gm.o \
	s_gnc.o \
	s_gnv.o \
	s_gplv.o \
	s_gr.o \
	s_grmd.o \
	s_grmdt.o \
	s_grmfb.o \
	s_grmp.o \
	s_grmt.o \
	s_grv.o \
	s_gtm.o \
	s_gtsa.o \
	s_gva.o \
	s_gvad.o \
	s_gvada.o \
	s_gvar.o \
	s_gvara.o \
	s_gvdr.o \
	s_gvea.o \
	s_gvex.o \
	s_gvlsa.o \
	s_gvn.o \
	s_gvp.o \
	s_gvrr.o \
	s_gvrra.o \
	s_gvsa.o \
	s_gvsl.o \
	s_gvsn.o \
	s_gvsr.o \
	s_gvsra.o \
	s_gvv.o \
	s_gvva.o \
	s_gvvx.o \
	s_i.o \
	s_ih.o \
	s_ini.o \
	s_irwar.o \
	s_it.o \
	s_itc.o \
	s_m.o \
	s_m_f.o \
	s_m_init.o \
	s_m_int.o \
	s_m_m.o \
	s_m_util.o \
	s_m_wsa.o \
	s_m_x.o \
	s_n2p.o \
	s_q.o \
	s_r.o \
	s_rdd.o \
	s_rmp1.o \
	s_rmp2.o \
	s_rrwa.o \
	s_sada.o \
	s_sav.o \
	s_sca.o \
	s_sccm.o \
	s_sccr.o \
	s_sccv.o \
	s_scmv.o \
	s_scmva.o \
	s_se.o \
	s_sesa.o \
	s_sfr.o \
	s_si.o \
	s_sia.o \
	s_sic.o \
	s_sk.o \
	s_skowa.o \
	s_sm.o \
	s_snc.o \
	s_snv.o \
	s_splv.o \
	s_sr.o \
	s_sra.o \
	s_srd.o \
	s_srmd.o \
	s_srmdt.o \
	s_srmfb.o \
	s_srmp.o \
	s_srmt.o \
	s_srv.o \
	s_stc.o \
	s_stm.o \
	s_stsa.o \
	s_sva.o \
	s_svad.o \
	s_svada.o \
	s_svar.o \
	s_svara.o \
	s_svdr.o \
	s_svlsa.o \
	s_svn.o \
	s_svp.o \
	s_svrra.o \
	s_svsa.o \
	s_svsl.o \
	s_svsn.o \
	s_svsr.o \
	s_svsra.o \
	s_svv.o \
	s_svva.o \
	s_w.o \
	s_w0.o \
	s_wp.o \
	sl_sva.o \
	sn_gva.o \
	sn_sva.o \
	spu.o \
	sr_gaks.o \
	sr_sva.o \
	st.o \
	zerobuf.o

IOP_LIB = libspu2.a

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/iop/Rules.lib.make
include $(PS2SDKSRC)/iop/Rules.make
include $(PS2SDKSRC)/iop/Rules.release
