EE_BIN   = ps2tests.elf
EE_OBJS  = runner.o testsuite.o 
EE_OBJS += stdio_tests.o

EE_INCS = 
EE_LIBS =

all: $(EE_BIN)

install:

clean:
	rm -f $(EE_BIN) $(EE_OBJS)

include Makefile.pref
include Makefile.eeglobal
