# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_BIN_ALTNAMES =

IOP_SRC_DIR = $(PS2SDKSRC)/iop/system/eesync/src/
IOP_INC_DIR = $(PS2SDKSRC)/iop/system/eesync/include/

EESYNC_WIPE_EE_KERNEL_SPACE ?= 0
EESYNC_SECRMAN_DUMMY ?= 0
EESYNC_REGISTER_EXPORTS ?= 0
EESYNC_CHECK_ILOADP ?= 0

include $(PS2SDKSRC)/iop/system/eesync/Makefile
