# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

IOP_PAR_DIR = $(PS2SDKSRC)/iop/fs/filexio
IOP_SRC_DIR = $(IOP_PAR_DIR)/src/
IOP_INC_DIR = $(IOP_PAR_DIR)/src/

IOP_BIN ?= fileXio_verbose.irx

DEBUG = 1
include $(IOP_PAR_DIR)/Makefile