# _____     ___ ____     ___ ____
#  ____|   |    ____|   |        | |____|
# |     ___|   |____ ___|    ____| |    \    PS2DEV Open Source Project.
#-----------------------------------------------------------------------
# Copyright 2001-2004, ps2dev - http://www.ps2dev.org
# Licenced under Academic Free License version 2.0
# Review ps2sdk README & LICENSE files for further details.

SUBDIRS = \
	alloc \
	dmacman \
	eesync \
	eesync-nano \
	excepman \
	heaplib \
	intrman \
	intrmanp \
	ioman \
	iomanx \
	iopmgr \
	loadcore \
	loadfile \
	modload \
	mtapman \
	padman \
	padman-old \
	reboot \
	rmman \
	rmtapman \
	rpadman \
	rsio2man \
	sbusintr \
	sifcmd \
	sifinit \
	sifman \
	siftoo \
	sio2log \
	sio2man \
	sio2man-old \
	ssbusc \
	stdio \
	sysclib \
	sysclib-full \
	sysclib-nano \
	threadman \
	timrman \
	timrmanp \
	udnl \
	udnl-t300 \
	vblank

include $(PS2SDKSRC)/Defs.make
include $(PS2SDKSRC)/Rules.make
